{{- if .Values.s3Storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmon.fullname" . }}-s3
  labels:
    {{- include "vmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: s3-api
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: s3-console
  selector:
    {{- include "vmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: s3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vmon.fullname" . }}-s3
  labels:
    {{- include "vmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
spec:
  serviceName: {{ include "vmon.fullname" . }}-s3
  replicas: 1
  selector:
    matchLabels:
      {{- include "vmon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: s3
  template:
    metadata:
      labels:
        {{- include "vmon.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: s3
    spec:
      containers:
        - name: minio
          image: "{{ .Values.s3Storage.image.repository }}:{{ .Values.s3Storage.image.tag }}"
          imagePullPolicy: {{ .Values.s3Storage.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - "minio server /data --console-address :9001"
          ports:
            - containerPort: 9000
              name: s3-api
            - containerPort: 9001
              name: s3-console
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "vmon.s3Secret" . }}
                  key: access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vmon.s3Secret" . }}
                  key: secret-key
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.s3Storage.persistence.storageClass }}
        storageClassName: "{{ .Values.s3Storage.persistence.storageClass }}"
        {{- end }}
        resources:
          requests:
            storage: "{{ .Values.s3Storage.persistence.size }}"
{{- end }}
