{{- if not .Values.existingSecret }}
{{- if lt (len .Values.nodes.apiToken) 16 }}
{{- fail "nodes.apiToken must contain at least 16 characters when existingSecret is empty" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vmon.fullname" . }}-api-secrets
  labels:
    {{- include "vmon.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.nodes.apiToken | b64enc | quote }}
  {{- if .Values.nodes.clientToken }}
  client-token: {{ .Values.nodes.clientToken | b64enc | quote }}
  {{- else }}
  client-token: ""
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vmon.fullname" . }}-postgres-secrets
  labels:
    {{- include "vmon.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if .Values.externalDatabase.password }}
  postgres-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- else }}
  postgres-password: ""
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vmon.fullname" . }}-s3-secrets
  labels:
    {{- include "vmon.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.s3Storage.enabled }}
  access-key: {{ .Values.s3Storage.auth.accessKey | b64enc | quote }}
  secret-key: {{ .Values.s3Storage.auth.secretKey | b64enc | quote }}
  {{- else if and .Values.externalS3.accessKey .Values.externalS3.secretKey }}
  access-key: {{ .Values.externalS3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.externalS3.secretKey | b64enc | quote }}
  {{- else }}
  access-key: ""
  secret-key: ""
  {{- end }}
{{- end }}
