# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vmon.v1 import api_pb2 as vmon_dot_v1_dot_api__pb2


class SandboxServiceStub:
    """gRPC surface of the vmon v1 API — the ONLY API. All clients speak gRPC:
    native HTTP/2 (h2c over TCP or UDS) for CLI/Python/Go, and a
    gRPC-over-WebSocket bridge (vmon/v1/bridge.proto, `GET /grpc`) for
    browsers/TypeScript. Only infrastructure surfaces remain plain HTTP:
    healthz, /metrics, the guest ports proxy, static UI, and mesh-internal
    template distribution.

    Documents that are schemaless JSON in the engine (sandbox views, create
    specs, bodies with flattened extras) travel as JSON strings — their schema
    is owned by the engine, not this file. Fully-typed REST bodies are proto
    messages here.

    Errors: RPCs fail with a gRPC status; the stable vmond error code
    (vmond/src/error.rs: not_found, not_running, busy, invalid, unsupported,
    unauthorized, engine) is carried in `vmon-code` response metadata.
    Status mapping: not_found→NOT_FOUND, invalid→INVALID_ARGUMENT,
    unauthorized→UNAUTHENTICATED, not_running→FAILED_PRECONDITION,
    busy→ABORTED, unsupported→UNIMPLEMENTED, engine→UNAVAILABLE.

    SandboxService provides RPCs to manage microVM sandboxes, perform file operations,
    stream logs, manage networks, and execute interactive processes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/vmon.v1.SandboxService/Create',
                request_serializer=vmon_dot_v1_dot_api__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/vmon.v1.SandboxService/List',
                request_serializer=vmon_dot_v1_dot_api__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/vmon.v1.SandboxService/Get',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/vmon.v1.SandboxService/Stop',
                request_serializer=vmon_dot_v1_dot_api__pb2.StopSandboxRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/vmon.v1.SandboxService/Remove',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Terminate = channel.unary_unary(
                '/vmon.v1.SandboxService/Terminate',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/vmon.v1.SandboxService/Pause',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/vmon.v1.SandboxService/Resume',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Extend = channel.unary_unary(
                '/vmon.v1.SandboxService/Extend',
                request_serializer=vmon_dot_v1_dot_api__pb2.ExtendSandboxRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/vmon.v1.SandboxService/Metrics',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Logs = channel.unary_stream(
                '/vmon.v1.SandboxService/Logs',
                request_serializer=vmon_dot_v1_dot_api__pb2.LogsRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.LogChunk.FromString,
                _registered_method=True)
        self.ExecCapture = channel.unary_unary(
                '/vmon.v1.SandboxService/ExecCapture',
                request_serializer=vmon_dot_v1_dot_api__pb2.ExecCaptureRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.ExecCaptureResponse.FromString,
                _registered_method=True)
        self.Exec = channel.stream_stream(
                '/vmon.v1.SandboxService/Exec',
                request_serializer=vmon_dot_v1_dot_api__pb2.ExecInput.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.Shell = channel.stream_stream(
                '/vmon.v1.SandboxService/Shell',
                request_serializer=vmon_dot_v1_dot_api__pb2.ExecInput.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.Attach = channel.unary_stream(
                '/vmon.v1.SandboxService/Attach',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.FileRead = channel.unary_unary(
                '/vmon.v1.SandboxService/FileRead',
                request_serializer=vmon_dot_v1_dot_api__pb2.FilePathRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.FileContent.FromString,
                _registered_method=True)
        self.FileWrite = channel.unary_unary(
                '/vmon.v1.SandboxService/FileWrite',
                request_serializer=vmon_dot_v1_dot_api__pb2.FileWriteRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.Ok.FromString,
                _registered_method=True)
        self.FileDelete = channel.unary_unary(
                '/vmon.v1.SandboxService/FileDelete',
                request_serializer=vmon_dot_v1_dot_api__pb2.FileDeleteRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.Ok.FromString,
                _registered_method=True)
        self.FileList = channel.unary_unary(
                '/vmon.v1.SandboxService/FileList',
                request_serializer=vmon_dot_v1_dot_api__pb2.FilePathRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.FileStat = channel.unary_unary(
                '/vmon.v1.SandboxService/FileStat',
                request_serializer=vmon_dot_v1_dot_api__pb2.FilePathRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.NetworkGet = channel.unary_unary(
                '/vmon.v1.SandboxService/NetworkGet',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.NetworkSet = channel.unary_unary(
                '/vmon.v1.SandboxService/NetworkSet',
                request_serializer=vmon_dot_v1_dot_api__pb2.NetworkSetRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Tunnels = channel.unary_unary(
                '/vmon.v1.SandboxService/Tunnels',
                request_serializer=vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Migrate = channel.unary_unary(
                '/vmon.v1.SandboxService/Migrate',
                request_serializer=vmon_dot_v1_dot_api__pb2.MigrateRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/vmon.v1.SandboxService/Snapshot',
                request_serializer=vmon_dot_v1_dot_api__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.SnapshotFs = channel.unary_unary(
                '/vmon.v1.SandboxService/SnapshotFs',
                request_serializer=vmon_dot_v1_dot_api__pb2.SnapshotFsRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)


class SandboxServiceServicer:
    """gRPC surface of the vmon v1 API — the ONLY API. All clients speak gRPC:
    native HTTP/2 (h2c over TCP or UDS) for CLI/Python/Go, and a
    gRPC-over-WebSocket bridge (vmon/v1/bridge.proto, `GET /grpc`) for
    browsers/TypeScript. Only infrastructure surfaces remain plain HTTP:
    healthz, /metrics, the guest ports proxy, static UI, and mesh-internal
    template distribution.

    Documents that are schemaless JSON in the engine (sandbox views, create
    specs, bodies with flattened extras) travel as JSON strings — their schema
    is owned by the engine, not this file. Fully-typed REST bodies are proto
    messages here.

    Errors: RPCs fail with a gRPC status; the stable vmond error code
    (vmond/src/error.rs: not_found, not_running, busy, invalid, unsupported,
    unauthorized, engine) is carried in `vmon-code` response metadata.
    Status mapping: not_found→NOT_FOUND, invalid→INVALID_ARGUMENT,
    unauthorized→UNAUTHENTICATED, not_running→FAILED_PRECONDITION,
    busy→ABORTED, unsupported→UNIMPLEMENTED, engine→UNAVAILABLE.

    SandboxService provides RPCs to manage microVM sandboxes, perform file operations,
    stream logs, manage networks, and execute interactive processes.
    """

    def Create(self, request, context):
        """Creates a new microVM sandbox instance.

        Replaces: POST /v1/sandboxes
        Errors:
        - `invalid` (INVALID_ARGUMENT): The create spec is invalid or malformed.
        - `busy` (ABORTED): Required resources are locked.
        - `engine` (UNAVAILABLE): Hypervisor allocation or creation failed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Lists all registered microVM sandboxes, optionally filtered by tags.

        Replaces: GET /v1/sandboxes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Retrieves the current state, metadata, and status of a specific microVM sandbox.

        Replaces: GET /v1/sandboxes/{id}
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Gracefully stops a running sandbox microVM.
        Sends a shutdown signal to the guest OS. If it fails to exit within a grace period,
        it may be forcefully terminated depending on configuration.

        Replaces: POST /v1/sandboxes/{id}/stop
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is already stopped.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Stops (if running) and removes a sandbox from the registry, freeing all non-persistent resources.

        Replaces: DELETE /v1/sandboxes/{id}
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Immediately terminates a sandbox microVM hypervisor process without graceful shutdown.
        Equivalent to pulling the power plug.

        Replaces: POST /v1/sandboxes/{id}/terminate
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Pauses the execution of all vCPUs in the sandbox.
        CPU threads are quiesced via signal (Linux) or hypervisor callback (macOS/HVF).

        Replaces: POST /v1/sandboxes/{id}/pause
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Resumes vCPU execution for a paused sandbox.

        Replaces: POST /v1/sandboxes/{id}/resume
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not in a paused state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Extend(self, request, context):
        """Extends the sandbox's remaining wall-clock time-to-live (TTL) by the specified duration.

        Replaces: POST /v1/sandboxes/{id}/extend
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Retrieves real-time performance and utilization metrics for the microVM.
        Includes CPU utilization, memory footprint, virtio block/net throughput, and guest metrics.

        Replaces: GET /v1/sandboxes/{id}/metrics
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logs(self, request, context):
        """Streams the console log output of the microVM.
        Supports streaming historical logs (via `tail`) and real-time output (via `follow`).

        Replaces: GET /v1/sandboxes/{id}/logs
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecCapture(self, request, context):
        """Executes a non-interactive command inside the guest via the guest agent and captures
        its complete exit status, stdout, and stderr.

        Replaces: POST /v1/sandboxes/{id}/exec
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running or guest agent is unreachable.
        - `invalid` (INVALID_ARGUMENT): Invalid command or arguments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request_iterator, context):
        """Opens a bidirectional, interactive execution stream inside the guest via the guest agent.
        Supports PTY/TTY allocation, real-time stdin write, resize, EOF signaling, and exit status streaming.
        The first `ExecInput` message sent MUST contain the `ExecStart` payload.

        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running or guest agent is unreachable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shell(self, request_iterator, context):
        """Opens an interactive shell session inside the guest.
        The first `ExecInput` message sent MUST contain the `shell_params_json` payload.
        The server emits a `Ready` frame containing the resolved sandbox ID before streaming I/O.

        Replaces: GET /v1/shell
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attach(self, request, context):
        """Attaches a read-only stream to the microVM serial console, forwarding guest kernel output and boot logs.

        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileRead(self, request, context):
        """Reads the complete contents of a file inside the guest sandbox filesystem.

        Errors:
        - `not_found` (NOT_FOUND): The sandbox or the specified file does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileWrite(self, request, context):
        """Writes or overwrites a file inside the guest sandbox filesystem.
        Creates parent directories if they do not exist.

        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDelete(self, request, context):
        """Deletes a file or directory inside the guest sandbox filesystem.

        Errors:
        - `not_found` (NOT_FOUND): The sandbox or the specified file/directory does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileList(self, request, context):
        """Lists files and directories within a given directory inside the guest sandbox.

        Errors:
        - `not_found` (NOT_FOUND): The sandbox or the specified path does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileStat(self, request, context):
        """Performs a metadata query (stat) on a file inside the guest sandbox (size, type, permissions, times).

        Errors:
        - `not_found` (NOT_FOUND): The sandbox or the specified file does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NetworkGet(self, request, context):
        """Retrieves the active network configuration, interfaces, and routing for the sandbox.

        Replaces: GET /v1/sandboxes/{id}/network
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NetworkSet(self, request, context):
        """Updates the network access controls, allowed CIDRs, and allowed domains for the sandbox.

        Replaces: PUT /v1/sandboxes/{id}/network
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `invalid` (INVALID_ARGUMENT): Invalid network rules or CIDR formats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tunnels(self, request, context):
        """Retrieves active network tunnels and port-forwardings mapped to the sandbox.

        Replaces: GET /v1/sandboxes/{id}/tunnels
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Migrate(self, request, context):
        """Initiates state migration of the sandbox to a target destination or host.

        Replaces: POST /v1/sandboxes/{id}/migrate
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `invalid` (INVALID_ARGUMENT): Target destination is invalid or unreachable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Captures a snapshot of the sandbox's memory, register, and device state.

        Replaces: POST /v1/sandboxes/{id}/snapshot
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not currently running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotFs(self, request, context):
        """Triggers a filesystem freeze and creates a filesystem-level snapshot on disk.

        Replaces: POST /v1/sandboxes/{id}/snapshot-fs
        Errors:
        - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
        - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.CreateSandboxRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ListSandboxesRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.StopSandboxRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Extend': grpc.unary_unary_rpc_method_handler(
                    servicer.Extend,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ExtendSandboxRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Logs': grpc.unary_stream_rpc_method_handler(
                    servicer.Logs,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.LogsRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.LogChunk.SerializeToString,
            ),
            'ExecCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecCapture,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ExecCaptureRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.ExecCaptureResponse.SerializeToString,
            ),
            'Exec': grpc.stream_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ExecInput.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.ExecOutput.SerializeToString,
            ),
            'Shell': grpc.stream_stream_rpc_method_handler(
                    servicer.Shell,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ExecInput.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.ExecOutput.SerializeToString,
            ),
            'Attach': grpc.unary_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.ExecOutput.SerializeToString,
            ),
            'FileRead': grpc.unary_unary_rpc_method_handler(
                    servicer.FileRead,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.FilePathRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.FileContent.SerializeToString,
            ),
            'FileWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.FileWrite,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.FileWriteRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.Ok.SerializeToString,
            ),
            'FileDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDelete,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.FileDeleteRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.Ok.SerializeToString,
            ),
            'FileList': grpc.unary_unary_rpc_method_handler(
                    servicer.FileList,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.FilePathRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'FileStat': grpc.unary_unary_rpc_method_handler(
                    servicer.FileStat,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.FilePathRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'NetworkGet': grpc.unary_unary_rpc_method_handler(
                    servicer.NetworkGet,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'NetworkSet': grpc.unary_unary_rpc_method_handler(
                    servicer.NetworkSet,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.NetworkSetRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Tunnels': grpc.unary_unary_rpc_method_handler(
                    servicer.Tunnels,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SandboxRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Migrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Migrate,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.MigrateRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SnapshotRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'SnapshotFs': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotFs,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.SnapshotFsRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vmon.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vmon.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService:
    """gRPC surface of the vmon v1 API — the ONLY API. All clients speak gRPC:
    native HTTP/2 (h2c over TCP or UDS) for CLI/Python/Go, and a
    gRPC-over-WebSocket bridge (vmon/v1/bridge.proto, `GET /grpc`) for
    browsers/TypeScript. Only infrastructure surfaces remain plain HTTP:
    healthz, /metrics, the guest ports proxy, static UI, and mesh-internal
    template distribution.

    Documents that are schemaless JSON in the engine (sandbox views, create
    specs, bodies with flattened extras) travel as JSON strings — their schema
    is owned by the engine, not this file. Fully-typed REST bodies are proto
    messages here.

    Errors: RPCs fail with a gRPC status; the stable vmond error code
    (vmond/src/error.rs: not_found, not_running, busy, invalid, unsupported,
    unauthorized, engine) is carried in `vmon-code` response metadata.
    Status mapping: not_found→NOT_FOUND, invalid→INVALID_ARGUMENT,
    unauthorized→UNAUTHENTICATED, not_running→FAILED_PRECONDITION,
    busy→ABORTED, unsupported→UNIMPLEMENTED, engine→UNAVAILABLE.

    SandboxService provides RPCs to manage microVM sandboxes, perform file operations,
    stream logs, manage networks, and execute interactive processes.
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Create',
            vmon_dot_v1_dot_api__pb2.CreateSandboxRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/List',
            vmon_dot_v1_dot_api__pb2.ListSandboxesRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Get',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Stop',
            vmon_dot_v1_dot_api__pb2.StopSandboxRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Remove',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Terminate',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Pause',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Resume',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Extend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Extend',
            vmon_dot_v1_dot_api__pb2.ExtendSandboxRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Metrics',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vmon.v1.SandboxService/Logs',
            vmon_dot_v1_dot_api__pb2.LogsRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.LogChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/ExecCapture',
            vmon_dot_v1_dot_api__pb2.ExecCaptureRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.ExecCaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vmon.v1.SandboxService/Exec',
            vmon_dot_v1_dot_api__pb2.ExecInput.SerializeToString,
            vmon_dot_v1_dot_api__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shell(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vmon.v1.SandboxService/Shell',
            vmon_dot_v1_dot_api__pb2.ExecInput.SerializeToString,
            vmon_dot_v1_dot_api__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vmon.v1.SandboxService/Attach',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/FileRead',
            vmon_dot_v1_dot_api__pb2.FilePathRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.FileContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/FileWrite',
            vmon_dot_v1_dot_api__pb2.FileWriteRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.Ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/FileDelete',
            vmon_dot_v1_dot_api__pb2.FileDeleteRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.Ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/FileList',
            vmon_dot_v1_dot_api__pb2.FilePathRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/FileStat',
            vmon_dot_v1_dot_api__pb2.FilePathRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NetworkGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/NetworkGet',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NetworkSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/NetworkSet',
            vmon_dot_v1_dot_api__pb2.NetworkSetRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tunnels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Tunnels',
            vmon_dot_v1_dot_api__pb2.SandboxRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Migrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Migrate',
            vmon_dot_v1_dot_api__pb2.MigrateRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/Snapshot',
            vmon_dot_v1_dot_api__pb2.SnapshotRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotFs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SandboxService/SnapshotFs',
            vmon_dot_v1_dot_api__pb2.SnapshotFsRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SnapshotServiceStub:
    """SnapshotService manages saved microVM snapshots, enabling restorations and high-density forks.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/vmon.v1.SnapshotService/List',
                request_serializer=vmon_dot_v1_dot_api__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.SnapshotList.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/vmon.v1.SnapshotService/Restore',
                request_serializer=vmon_dot_v1_dot_api__pb2.RestoreSnapshotRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Fork = channel.unary_unary(
                '/vmon.v1.SnapshotService/Fork',
                request_serializer=vmon_dot_v1_dot_api__pb2.ForkSnapshotRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)


class SnapshotServiceServicer:
    """SnapshotService manages saved microVM snapshots, enabling restorations and high-density forks.
    """

    def List(self, request, context):
        """Lists all snapshots currently registered in the engine.

        Replaces: GET /v1/snapshots
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Restores a microVM sandbox instance from a previously captured snapshot.

        Replaces: POST /v1/snapshots/{name}/restore
        Errors:
        - `not_found` (NOT_FOUND): The specified snapshot name does not exist.
        - `invalid` (INVALID_ARGUMENT): Invalid configuration parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fork(self, request, context):
        """Rapidly forks one or more new sandbox instances from an existing snapshot.
        Under the hood, this utilizes copy-on-write sharing for high density and instant startup.

        Replaces: POST /v1/snapshots/{name}/fork
        Errors:
        - `not_found` (NOT_FOUND): The specified snapshot name does not exist.
        - `invalid` (INVALID_ARGUMENT): Invalid count or target configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.SnapshotList.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.RestoreSnapshotRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Fork': grpc.unary_unary_rpc_method_handler(
                    servicer.Fork,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ForkSnapshotRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vmon.v1.SnapshotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vmon.v1.SnapshotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SnapshotService:
    """SnapshotService manages saved microVM snapshots, enabling restorations and high-density forks.
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SnapshotService/List',
            vmon_dot_v1_dot_api__pb2.ListSnapshotsRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.SnapshotList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SnapshotService/Restore',
            vmon_dot_v1_dot_api__pb2.RestoreSnapshotRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SnapshotService/Fork',
            vmon_dot_v1_dot_api__pb2.ForkSnapshotRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VolumeServiceStub:
    """VolumeService provides RPCs for managing persistent block storage volumes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/vmon.v1.VolumeService/List',
                request_serializer=vmon_dot_v1_dot_api__pb2.ListVolumesRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.VolumeList.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/vmon.v1.VolumeService/Create',
                request_serializer=vmon_dot_v1_dot_api__pb2.VolumeRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.Ok.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/vmon.v1.VolumeService/Delete',
                request_serializer=vmon_dot_v1_dot_api__pb2.VolumeRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.Ok.FromString,
                _registered_method=True)


class VolumeServiceServicer:
    """VolumeService provides RPCs for managing persistent block storage volumes.
    """

    def List(self, request, context):
        """Lists all persistent volumes currently registered in the engine registry.

        Replaces: GET /v1/volumes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Creates a new persistent block storage volume.

        Replaces: POST /v1/volumes
        Errors:
        - `invalid` (INVALID_ARGUMENT): Invalid volume name, size, or parameters.
        - `busy` (ABORTED): Volume with the same name already exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Deletes a persistent block storage volume, permanently freeing its underlying disk storage.

        Replaces: DELETE /v1/volumes/{name}
        Errors:
        - `not_found` (NOT_FOUND): The specified volume does not exist.
        - `busy` (ABORTED): The volume is currently attached to a sandbox and cannot be deleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VolumeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ListVolumesRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.VolumeList.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.VolumeRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.Ok.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.VolumeRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.Ok.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vmon.v1.VolumeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vmon.v1.VolumeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VolumeService:
    """VolumeService provides RPCs for managing persistent block storage volumes.
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.VolumeService/List',
            vmon_dot_v1_dot_api__pb2.ListVolumesRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.VolumeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.VolumeService/Create',
            vmon_dot_v1_dot_api__pb2.VolumeRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.Ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.VolumeService/Delete',
            vmon_dot_v1_dot_api__pb2.VolumeRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.Ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PoolServiceStub:
    """PoolService manages warm pools of standby microVMs to eliminate cold-start latency.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/vmon.v1.PoolService/List',
                request_serializer=vmon_dot_v1_dot_api__pb2.ListPoolsRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/vmon.v1.PoolService/Set',
                request_serializer=vmon_dot_v1_dot_api__pb2.PoolSetRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/vmon.v1.PoolService/Delete',
                request_serializer=vmon_dot_v1_dot_api__pb2.PoolRef.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.Ok.FromString,
                _registered_method=True)


class PoolServiceServicer:
    """PoolService manages warm pools of standby microVMs to eliminate cold-start latency.
    """

    def List(self, request, context):
        """Lists configured warm pools and their standby microVM counts.

        Replaces: GET /v1/pools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Creates or updates a warm pool configuration, adjusting the standby target size.

        Replaces: PUT /v1/pools/{reference}
        Errors:
        - `invalid` (INVALID_ARGUMENT): Invalid pool definition or size.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Deletes a warm pool and tears down all pre-warmed standby sandboxes within it.

        Replaces: DELETE /v1/pools/{reference}
        Errors:
        - `not_found` (NOT_FOUND): The specified pool reference does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.ListPoolsRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.PoolSetRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.PoolRef.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.Ok.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vmon.v1.PoolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vmon.v1.PoolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoolService:
    """PoolService manages warm pools of standby microVMs to eliminate cold-start latency.
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.PoolService/List',
            vmon_dot_v1_dot_api__pb2.ListPoolsRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.PoolService/Set',
            vmon_dot_v1_dot_api__pb2.PoolSetRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.PoolService/Delete',
            vmon_dot_v1_dot_api__pb2.PoolRef.SerializeToString,
            vmon_dot_v1_dot_api__pb2.Ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SystemServiceStub:
    """SystemService provides administrative queries and streams engine-wide event feeds.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/vmon.v1.SystemService/Info',
                request_serializer=vmon_dot_v1_dot_api__pb2.InfoRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.Events = channel.unary_stream(
                '/vmon.v1.SystemService/Events',
                request_serializer=vmon_dot_v1_dot_api__pb2.EventsRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)
        self.MeshStatus = channel.unary_unary(
                '/vmon.v1.SystemService/MeshStatus',
                request_serializer=vmon_dot_v1_dot_api__pb2.MeshStatusRequest.SerializeToString,
                response_deserializer=vmon_dot_v1_dot_api__pb2.JsonView.FromString,
                _registered_method=True)


class SystemServiceServicer:
    """SystemService provides administrative queries and streams engine-wide event feeds.
    """

    def Info(self, request, context):
        """Retrieves general status, version, capabilities, and system metrics from the host engine.

        Replaces: GET /v1/info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Events(self, request, context):
        """Streams real-time engine-wide events (e.g. sandbox boots, shutdowns, updates).

        Replaces: GET /v1/events (SSE)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MeshStatus(self, request, context):
        """Mesh roster/status document for SDK endpoint discovery.

        Replaces: GET /v1/mesh/status (other /v1/mesh/* admin routes are
        mesh-internal and remain HTTP).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.InfoRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'Events': grpc.unary_stream_rpc_method_handler(
                    servicer.Events,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.EventsRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
            'MeshStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.MeshStatus,
                    request_deserializer=vmon_dot_v1_dot_api__pb2.MeshStatusRequest.FromString,
                    response_serializer=vmon_dot_v1_dot_api__pb2.JsonView.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vmon.v1.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vmon.v1.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService:
    """SystemService provides administrative queries and streams engine-wide event feeds.
    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SystemService/Info',
            vmon_dot_v1_dot_api__pb2.InfoRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Events(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vmon.v1.SystemService/Events',
            vmon_dot_v1_dot_api__pb2.EventsRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MeshStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vmon.v1.SystemService/MeshStatus',
            vmon_dot_v1_dot_api__pb2.MeshStatusRequest.SerializeToString,
            vmon_dot_v1_dot_api__pb2.JsonView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
