encryptionsalt: v1:3xmdzguBOzs=:v1:36BldbTHVnoi06p0:tZGeleDgkC8kWBBTrNaAvDdTLGBdrw==
config:
  aws:region: eu-central-1
  vibevmm-orch:allowedCidr: 84.115.211.6/32
  vibevmm-orch:workerMin: "4"
  vibevmm-orch:workerMax: "4"
  vibevmm-orch:maxSandboxesPerWorker: "0"
  vibevmm-orch:targetUtil: "0.5"
  vibevmm-orch:schedulerCount: "1"
  vibevmm-orch:arch: x86_64
  vibevmm-orch:workerInstanceType: m7i.2xlarge
  vibevmm-orch:schedulerInstanceType: t3.small
  vibevmm-orch:stateInstanceType: t3.small
  vibevmm-orch:binaryS3Uri: s3://vibevmm-orch-adf9c02f/vmon-x86_64
  vibevmm-orch:assetsS3Uri: s3://vibevmm-orch-adf9c02f/vmon-assets-x86_64.tar.gz
