// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vmon/v1/api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stream identifies the source channel of streamed output data.
type Stream int32

const (
	// Unspecified stream. Used as a fallback or default value.
	Stream_STREAM_UNSPECIFIED Stream = 0
	// Standard output stream (stdout) of the executed process.
	Stream_STREAM_STDOUT Stream = 1
	// Standard error stream (stderr) of the executed process.
	Stream_STREAM_STDERR Stream = 2
	// Hypervisor-level raw serial console stream of the microVM.
	Stream_STREAM_CONSOLE Stream = 3
)

// Enum value maps for Stream.
var (
	Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STREAM_STDOUT",
		2: "STREAM_STDERR",
		3: "STREAM_CONSOLE",
	}
	Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STREAM_STDOUT":      1,
		"STREAM_STDERR":      2,
		"STREAM_CONSOLE":     3,
	}
)

func (x Stream) Enum() *Stream {
	p := new(Stream)
	*p = x
	return p
}

func (x Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_vmon_v1_api_proto_enumTypes[0].Descriptor()
}

func (Stream) Type() protoreflect.EnumType {
	return &file_vmon_v1_api_proto_enumTypes[0]
}

func (x Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stream.Descriptor instead.
func (Stream) EnumDescriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{0}
}

// JsonView represents a schemaless JSON document string.
// Used for documents whose schemas are fully managed by the engine (e.g. sandbox view, metrics).
type JsonView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON-serialized object content.
	Json          string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonView) Reset() {
	*x = JsonView{}
	mi := &file_vmon_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonView) ProtoMessage() {}

func (x *JsonView) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonView.ProtoReflect.Descriptor instead.
func (*JsonView) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *JsonView) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

// Ok represents a successful empty response.
type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_vmon_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{1}
}

// SandboxRef references a specific sandbox instance by its ID.
type SandboxRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxRef) Reset() {
	*x = SandboxRef{}
	mi := &file_vmon_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxRef) ProtoMessage() {}

func (x *SandboxRef) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxRef.ProtoReflect.Descriptor instead.
func (*SandboxRef) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CreateSandboxRequest wraps the configuration JSON for sandbox creation.
type CreateSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SandboxCreate JSON document payload — matches the former REST schema.
	SpecJson      string `protobuf:"bytes,1,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSandboxRequest) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

// ListSandboxesRequest specifies filters for listing sandbox instances.
type ListSandboxesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tag filter items (format: `key=value`). If empty, lists all sandboxes.
	Tags          []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListSandboxesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ListSandboxesResponse wraps the list of retrieved sandbox configurations.
type ListSandboxesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An array of JSON-serialized sandbox view documents.
	SandboxesJson []string `protobuf:"bytes,1,rep,name=sandboxes_json,json=sandboxesJson,proto3" json:"sandboxes_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_vmon_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListSandboxesResponse) GetSandboxesJson() []string {
	if x != nil {
		return x.SandboxesJson
	}
	return nil
}

// StopSandboxRequest represents parameters to gracefully stop a sandbox.
type StopSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional exit/return code of the foreground CLI process to preserve in metrics and logs.
	Returncode    *int64 `protobuf:"varint,2,opt,name=returncode,proto3,oneof" json:"returncode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *StopSandboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopSandboxRequest) GetReturncode() int64 {
	if x != nil && x.Returncode != nil {
		return *x.Returncode
	}
	return 0
}

// ExtendSandboxRequest represents parameters to extend the TTL of a sandbox.
type ExtendSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The duration to extend the sandbox's lifespan, in seconds.
	Secs          uint64 `protobuf:"varint,2,opt,name=secs,proto3" json:"secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendSandboxRequest) Reset() {
	*x = ExtendSandboxRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSandboxRequest) ProtoMessage() {}

func (x *ExtendSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendSandboxRequest.ProtoReflect.Descriptor instead.
func (*ExtendSandboxRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *ExtendSandboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtendSandboxRequest) GetSecs() uint64 {
	if x != nil {
		return x.Secs
	}
	return 0
}

// LogsRequest represents criteria for streaming microVM logs.
type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// If true, the stream remains open and continues to send new console lines in real time (follow).
	Follow bool `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	// If set, specifies the number of historical console lines to retrieve before streaming new logs.
	Tail          *uint64 `protobuf:"varint,3,opt,name=tail,proto3,oneof" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *LogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() uint64 {
	if x != nil && x.Tail != nil {
		return *x.Tail
	}
	return 0
}

// LogChunk represents a binary slice of streamed console logs.
type LogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw byte payload containing the console output segment.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_vmon_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ExecStart defines execution parameters for a command run inside the guest.
type ExecStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command-line command and its arguments to run (e.g., ["sh", "-c", "ls -l"]).
	Cmd []string `protobuf:"bytes,1,rep,name=cmd,proto3" json:"cmd,omitempty"`
	// Optional absolute path of the directory inside the guest to start execution in.
	Workdir *string `protobuf:"bytes,2,opt,name=workdir,proto3,oneof" json:"workdir,omitempty"`
	// Optional key-value environment variables to inject into the executed process.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional process timeout duration in seconds. If exceeded, the process is terminated.
	Timeout *float64 `protobuf:"fixed64,4,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	// If true, allocates a pseudoterminal (PTY/TTY) inside the guest for interactive sessions.
	Tty bool `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	// Target sandbox. Required in the first ExecInput of SandboxService.Exec
	// (INVALID_ARGUMENT when empty); ignored under ExecCaptureRequest, whose
	// own `id` is authoritative.
	SandboxId     string `protobuf:"bytes,6,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_vmon_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *ExecStart) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ExecStart) GetWorkdir() string {
	if x != nil && x.Workdir != nil {
		return *x.Workdir
	}
	return ""
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecStart) GetTimeout() float64 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStart) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

// ExecCaptureRequest represents execution parameters for buffered output capture.
type ExecCaptureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The execution configuration.
	Exec          *ExecStart `protobuf:"bytes,2,opt,name=exec,proto3" json:"exec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCaptureRequest) Reset() {
	*x = ExecCaptureRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCaptureRequest) ProtoMessage() {}

func (x *ExecCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCaptureRequest.ProtoReflect.Descriptor instead.
func (*ExecCaptureRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *ExecCaptureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecCaptureRequest) GetExec() *ExecStart {
	if x != nil {
		return x.Exec
	}
	return nil
}

// ExecCaptureResponse contains the final status and complete buffered outputs of a command.
type ExecCaptureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The process termination status exit code.
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// The POSIX signal that terminated the process, if applicable.
	Signal *int64 `protobuf:"varint,2,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	// Complete stdout buffer contents captured from the command.
	Stdout []byte `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Complete stderr buffer contents captured from the command (empty if TTY is allocated).
	Stderr        []byte `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCaptureResponse) Reset() {
	*x = ExecCaptureResponse{}
	mi := &file_vmon_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCaptureResponse) ProtoMessage() {}

func (x *ExecCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCaptureResponse.ProtoReflect.Descriptor instead.
func (*ExecCaptureResponse) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *ExecCaptureResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExecCaptureResponse) GetSignal() int64 {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return 0
}

func (x *ExecCaptureResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecCaptureResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

// ExecInput represents the client-to-server payload in interactive execution streams.
type ExecInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interactive input event.
	//
	// Types that are valid to be assigned to Input:
	//
	//	*ExecInput_Start
	//	*ExecInput_ShellParamsJson
	//	*ExecInput_Stdin
	//	*ExecInput_Eof
	//	*ExecInput_Resize
	Input         isExecInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInput) Reset() {
	*x = ExecInput{}
	mi := &file_vmon_v1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInput) ProtoMessage() {}

func (x *ExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInput.ProtoReflect.Descriptor instead.
func (*ExecInput) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *ExecInput) GetInput() isExecInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecInput) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecInput) GetShellParamsJson() string {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_ShellParamsJson); ok {
			return x.ShellParamsJson
		}
	}
	return ""
}

func (x *ExecInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecInput) GetEof() *Eof {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Eof); ok {
			return x.Eof
		}
	}
	return nil
}

func (x *ExecInput) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecInput_Input interface {
	isExecInput_Input()
}

type ExecInput_Start struct {
	// Required first message on the `/exec` stream to initiate execution.
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecInput_ShellParamsJson struct {
	// Required first message on the `/shell` stream to initialize the shell.
	// Contains JSON configuration (e.g. "{}" for defaults).
	ShellParamsJson string `protobuf:"bytes,2,opt,name=shell_params_json,json=shellParamsJson,proto3,oneof"`
}

type ExecInput_Stdin struct {
	// A chunk of raw standard input (stdin) bytes to write to the guest process.
	Stdin []byte `protobuf:"bytes,3,opt,name=stdin,proto3,oneof"`
}

type ExecInput_Eof struct {
	// Signals the closing of the standard input stream (EOF) from the client.
	Eof *Eof `protobuf:"bytes,4,opt,name=eof,proto3,oneof"`
}

type ExecInput_Resize struct {
	// Requests a change in the guest's pseudoterminal (pty) window dimensions.
	Resize *Resize `protobuf:"bytes,5,opt,name=resize,proto3,oneof"`
}

func (*ExecInput_Start) isExecInput_Input() {}

func (*ExecInput_ShellParamsJson) isExecInput_Input() {}

func (*ExecInput_Stdin) isExecInput_Input() {}

func (*ExecInput_Eof) isExecInput_Input() {}

func (*ExecInput_Resize) isExecInput_Input() {}

// ExecOutput represents the server-to-client payload in interactive execution streams.
type ExecOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interactive output event.
	//
	// Types that are valid to be assigned to Output:
	//
	//	*ExecOutput_Chunk
	//	*ExecOutput_Exit
	//	*ExecOutput_Ready
	Output        isExecOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_vmon_v1_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{14}
}

func (x *ExecOutput) GetOutput() isExecOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecOutput) GetChunk() *Output {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ExecOutput) GetExit() *Exit {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *ExecOutput) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

type isExecOutput_Output interface {
	isExecOutput_Output()
}

type ExecOutput_Chunk struct {
	// A chunk of standard output or standard error streamed from the guest.
	Chunk *Output `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type ExecOutput_Exit struct {
	// Indicates that the guest process has terminated.
	Exit *Exit `protobuf:"bytes,2,opt,name=exit,proto3,oneof"`
}

type ExecOutput_Ready struct {
	// Emitted exactly once upon successful session initialization before any chunks are sent.
	Ready *Ready `protobuf:"bytes,3,opt,name=ready,proto3,oneof"`
}

func (*ExecOutput_Chunk) isExecOutput_Output() {}

func (*ExecOutput_Exit) isExecOutput_Output() {}

func (*ExecOutput_Ready) isExecOutput_Output() {}

// FilePathRequest specifies a file path within a sandbox's guest filesystem.
type FilePathRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The target absolute path inside the guest.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePathRequest) Reset() {
	*x = FilePathRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePathRequest) ProtoMessage() {}

func (x *FilePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePathRequest.ProtoReflect.Descriptor instead.
func (*FilePathRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{15}
}

func (x *FilePathRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilePathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// FileContent contains raw file data read from the guest.
type FileContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw file data payload.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_vmon_v1_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{16}
}

func (x *FileContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// FileWriteRequest encapsulates data to write to a path in the guest filesystem.
type FileWriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The target absolute path inside the guest.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// The raw data payload to write.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{17}
}

func (x *FileWriteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// FileDeleteRequest represents parameters for deleting a guest file.
type FileDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The target absolute path inside the guest.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// If true, recursively deletes directories and their contents.
	Recursive     bool `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteRequest) Reset() {
	*x = FileDeleteRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteRequest) ProtoMessage() {}

func (x *FileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteRequest.ProtoReflect.Descriptor instead.
func (*FileDeleteRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{18}
}

func (x *FileDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileDeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDeleteRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// StringList represents a list of string values. Used to distinguish between
// an empty list and an omitted/absent list (for presence-aware updates).
type StringList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The string values.
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_vmon_v1_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{19}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// NetworkSetRequest represents network firewall and access rules updates for a sandbox.
type NetworkSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional: if set, blocks or allows external network access for the sandbox.
	BlockNetwork *bool `protobuf:"varint,2,opt,name=block_network,json=blockNetwork,proto3,oneof" json:"block_network,omitempty"`
	// Presence-aware CIDR block IP whitelist. If omitted, CIDR allowlist is left unchanged.
	CidrAllow *StringList `protobuf:"bytes,3,opt,name=cidr_allow,json=cidrAllow,proto3" json:"cidr_allow,omitempty"`
	// Presence-aware domain name whitelist. If omitted, domain allowlist is left unchanged.
	DomainAllow   *StringList `protobuf:"bytes,4,opt,name=domain_allow,json=domainAllow,proto3" json:"domain_allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSetRequest) Reset() {
	*x = NetworkSetRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSetRequest) ProtoMessage() {}

func (x *NetworkSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSetRequest.ProtoReflect.Descriptor instead.
func (*NetworkSetRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{20}
}

func (x *NetworkSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkSetRequest) GetBlockNetwork() bool {
	if x != nil && x.BlockNetwork != nil {
		return *x.BlockNetwork
	}
	return false
}

func (x *NetworkSetRequest) GetCidrAllow() *StringList {
	if x != nil {
		return x.CidrAllow
	}
	return nil
}

func (x *NetworkSetRequest) GetDomainAllow() *StringList {
	if x != nil {
		return x.DomainAllow
	}
	return nil
}

// MigrateRequest represents parameters to migrate a sandbox.
type MigrateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox to migrate.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The destination address or host URI.
	Target        string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{21}
}

func (x *MigrateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MigrateRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// SnapshotRequest defines snapshot creation parameters.
type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional name to assign to the snapshot. If omitted, an auto-generated name is used.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// If true, stops the sandbox microVM immediately after taking the snapshot.
	Stop          bool `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{22}
}

func (x *SnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SnapshotRequest) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

// SnapshotFsRequest defines filesystem-level freeze/snapshot parameters.
type SnapshotFsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target sandbox.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional name to assign to the filesystem snapshot.
	Name          *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFsRequest) Reset() {
	*x = SnapshotFsRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFsRequest) ProtoMessage() {}

func (x *SnapshotFsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFsRequest.ProtoReflect.Descriptor instead.
func (*SnapshotFsRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{23}
}

func (x *SnapshotFsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotFsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// ListSnapshotsRequest represents a request to list snapshots.
type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{24}
}

// SnapshotList wraps the list of registered snapshots.
type SnapshotList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of snapshot names.
	Snapshots     []string `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotList) Reset() {
	*x = SnapshotList{}
	mi := &file_vmon_v1_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotList) ProtoMessage() {}

func (x *SnapshotList) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotList.ProtoReflect.Descriptor instead.
func (*SnapshotList) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{25}
}

func (x *SnapshotList) GetSnapshots() []string {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// RestoreSnapshotRequest represents parameters to restore a sandbox from a snapshot.
type RestoreSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier or name of the target snapshot.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON configuration string mapping to RestoreBody (defines targets, pool assignments, and options).
	BodyJson      string `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotRequest) Reset() {
	*x = RestoreSnapshotRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotRequest) ProtoMessage() {}

func (x *RestoreSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{26}
}

func (x *RestoreSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

// ForkSnapshotRequest represents parameters to clone/fork a sandbox from a snapshot.
type ForkSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier or name of the source snapshot.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON configuration string mapping to ForkBody (defines copy-on-write target counts and settings).
	BodyJson      string `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkSnapshotRequest) Reset() {
	*x = ForkSnapshotRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkSnapshotRequest) ProtoMessage() {}

func (x *ForkSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ForkSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{27}
}

func (x *ForkSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForkSnapshotRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

// ListVolumesRequest represents a request to list persistent volumes.
type ListVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{28}
}

// VolumeList wraps the list of persistent volumes.
type VolumeList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of persistent volume names.
	Volumes       []string `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeList) Reset() {
	*x = VolumeList{}
	mi := &file_vmon_v1_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeList) ProtoMessage() {}

func (x *VolumeList) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeList.ProtoReflect.Descriptor instead.
func (*VolumeList) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{29}
}

func (x *VolumeList) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

// VolumeRef represents a reference to a persistent volume.
type VolumeRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique name of the persistent volume.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeRef) Reset() {
	*x = VolumeRef{}
	mi := &file_vmon_v1_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRef) ProtoMessage() {}

func (x *VolumeRef) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRef.ProtoReflect.Descriptor instead.
func (*VolumeRef) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{30}
}

func (x *VolumeRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListPoolsRequest represents a request to list warm pools.
type ListPoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsRequest) Reset() {
	*x = ListPoolsRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsRequest) ProtoMessage() {}

func (x *ListPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsRequest.ProtoReflect.Descriptor instead.
func (*ListPoolsRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{31}
}

// PoolSetRequest represents configuration for creating/updating a warm pool.
type PoolSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The reference identifier of the warm pool.
	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	// JSON configuration string mapping to PoolPutBody (defines standby sandbox pool size and specs).
	BodyJson      string `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolSetRequest) Reset() {
	*x = PoolSetRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolSetRequest) ProtoMessage() {}

func (x *PoolSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolSetRequest.ProtoReflect.Descriptor instead.
func (*PoolSetRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{32}
}

func (x *PoolSetRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *PoolSetRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

// PoolRef represents a reference to a warm pool.
type PoolRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The reference identifier of the target warm pool.
	Reference     string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolRef) Reset() {
	*x = PoolRef{}
	mi := &file_vmon_v1_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolRef) ProtoMessage() {}

func (x *PoolRef) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolRef.ProtoReflect.Descriptor instead.
func (*PoolRef) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{33}
}

func (x *PoolRef) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

// InfoRequest represents a request for server metadata.
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{34}
}

// MeshStatusRequest represents a request for the mesh roster/status document.
type MeshStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshStatusRequest) Reset() {
	*x = MeshStatusRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshStatusRequest) ProtoMessage() {}

func (x *MeshStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshStatusRequest.ProtoReflect.Descriptor instead.
func (*MeshStatusRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{35}
}

// EventsRequest represents a request to stream system events.
type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_vmon_v1_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{36}
}

// Eof signals the completion of the standard input stream (EOF) from client to server.
type Eof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eof) Reset() {
	*x = Eof{}
	mi := &file_vmon_v1_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eof) ProtoMessage() {}

func (x *Eof) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eof.ProtoReflect.Descriptor instead.
func (*Eof) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{37}
}

// Resize defines the dimensions of a pseudoterminal (pty) window.
type Resize struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of terminal rows. Must be in the range [1, 65535].
	// Values outside this range will cause the server to reject the resize request.
	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	// The number of terminal columns. Must be in the range [1, 65535].
	// Values outside this range will cause the server to reject the resize request.
	Cols          uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_vmon_v1_api_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{38}
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// Output encapsulates output data streamed from a running guest process or the hypervisor console.
type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stream source of the output data (stdout, stderr, or console).
	Stream Stream `protobuf:"varint,1,opt,name=stream,proto3,enum=vmon.v1.Stream" json:"stream,omitempty"`
	// The raw byte payload of the output chunk.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_vmon_v1_api_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{39}
}

func (x *Output) GetStream() Stream {
	if x != nil {
		return x.Stream
	}
	return Stream_STREAM_UNSPECIFIED
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Exit represents the termination status of an executed guest process.
type Exit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The process exit status code. Typically 0 for success, and non-zero for failures.
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// The POSIX signal number that terminated the process, if applicable (e.g. SIGKILL, SIGSEGV).
	// Omitted if the process exited voluntarily.
	Signal        *int64 `protobuf:"varint,2,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exit) Reset() {
	*x = Exit{}
	mi := &file_vmon_v1_api_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exit) ProtoMessage() {}

func (x *Exit) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exit.ProtoReflect.Descriptor instead.
func (*Exit) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{40}
}

func (x *Exit) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Exit) GetSignal() int64 {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return 0
}

// Ready signals that the interactive session has been initialized successfully.
type Ready struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the active microVM sandbox.
	SandboxId     string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_vmon_v1_api_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_vmon_v1_api_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_vmon_v1_api_proto_rawDescGZIP(), []int{41}
}

func (x *Ready) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

var File_vmon_v1_api_proto protoreflect.FileDescriptor

const file_vmon_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x11vmon/v1/api.proto\x12\avmon.v1\"\x1e\n" +
	"\bJsonView\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\x04\n" +
	"\x02Ok\"\x1c\n" +
	"\n" +
	"SandboxRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x14CreateSandboxRequest\x12\x1b\n" +
	"\tspec_json\x18\x01 \x01(\tR\bspecJson\"*\n" +
	"\x14ListSandboxesRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\">\n" +
	"\x15ListSandboxesResponse\x12%\n" +
	"\x0esandboxes_json\x18\x01 \x03(\tR\rsandboxesJson\"X\n" +
	"\x12StopSandboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\n" +
	"returncode\x18\x02 \x01(\x03H\x00R\n" +
	"returncode\x88\x01\x01B\r\n" +
	"\v_returncode\":\n" +
	"\x14ExtendSandboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04secs\x18\x02 \x01(\x04R\x04secs\"W\n" +
	"\vLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x17\n" +
	"\x04tail\x18\x03 \x01(\x04H\x00R\x04tail\x88\x01\x01B\a\n" +
	"\x05_tail\"\x1e\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x8b\x02\n" +
	"\tExecStart\x12\x10\n" +
	"\x03cmd\x18\x01 \x03(\tR\x03cmd\x12\x1d\n" +
	"\aworkdir\x18\x02 \x01(\tH\x00R\aworkdir\x88\x01\x01\x12-\n" +
	"\x03env\x18\x03 \x03(\v2\x1b.vmon.v1.ExecStart.EnvEntryR\x03env\x12\x1d\n" +
	"\atimeout\x18\x04 \x01(\x01H\x01R\atimeout\x88\x01\x01\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x06 \x01(\tR\tsandboxId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_workdirB\n" +
	"\n" +
	"\b_timeout\"L\n" +
	"\x12ExecCaptureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04exec\x18\x02 \x01(\v2\x12.vmon.v1.ExecStartR\x04exec\"\x81\x01\n" +
	"\x13ExecCaptureResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x1b\n" +
	"\x06signal\x18\x02 \x01(\x03H\x00R\x06signal\x88\x01\x01\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\fR\x06stderrB\t\n" +
	"\a_signal\"\xd3\x01\n" +
	"\tExecInput\x12*\n" +
	"\x05start\x18\x01 \x01(\v2\x12.vmon.v1.ExecStartH\x00R\x05start\x12,\n" +
	"\x11shell_params_json\x18\x02 \x01(\tH\x00R\x0fshellParamsJson\x12\x16\n" +
	"\x05stdin\x18\x03 \x01(\fH\x00R\x05stdin\x12 \n" +
	"\x03eof\x18\x04 \x01(\v2\f.vmon.v1.EofH\x00R\x03eof\x12)\n" +
	"\x06resize\x18\x05 \x01(\v2\x0f.vmon.v1.ResizeH\x00R\x06resizeB\a\n" +
	"\x05input\"\x8c\x01\n" +
	"\n" +
	"ExecOutput\x12'\n" +
	"\x05chunk\x18\x01 \x01(\v2\x0f.vmon.v1.OutputH\x00R\x05chunk\x12#\n" +
	"\x04exit\x18\x02 \x01(\v2\r.vmon.v1.ExitH\x00R\x04exit\x12&\n" +
	"\x05ready\x18\x03 \x01(\v2\x0e.vmon.v1.ReadyH\x00R\x05readyB\b\n" +
	"\x06output\"5\n" +
	"\x0fFilePathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"!\n" +
	"\vFileContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"J\n" +
	"\x10FileWriteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"U\n" +
	"\x11FileDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xcb\x01\n" +
	"\x11NetworkSetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\rblock_network\x18\x02 \x01(\bH\x00R\fblockNetwork\x88\x01\x01\x122\n" +
	"\n" +
	"cidr_allow\x18\x03 \x01(\v2\x13.vmon.v1.StringListR\tcidrAllow\x126\n" +
	"\fdomain_allow\x18\x04 \x01(\v2\x13.vmon.v1.StringListR\vdomainAllowB\x10\n" +
	"\x0e_block_network\"8\n" +
	"\x0eMigrateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"W\n" +
	"\x0fSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x12\n" +
	"\x04stop\x18\x03 \x01(\bR\x04stopB\a\n" +
	"\x05_name\"E\n" +
	"\x11SnapshotFsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"\x16\n" +
	"\x14ListSnapshotsRequest\",\n" +
	"\fSnapshotList\x12\x1c\n" +
	"\tsnapshots\x18\x01 \x03(\tR\tsnapshots\"I\n" +
	"\x16RestoreSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\tR\bbodyJson\"F\n" +
	"\x13ForkSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\tR\bbodyJson\"\x14\n" +
	"\x12ListVolumesRequest\"&\n" +
	"\n" +
	"VolumeList\x12\x18\n" +
	"\avolumes\x18\x01 \x03(\tR\avolumes\"\x1f\n" +
	"\tVolumeRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x12\n" +
	"\x10ListPoolsRequest\"K\n" +
	"\x0ePoolSetRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\tR\bbodyJson\"'\n" +
	"\aPoolRef\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"\r\n" +
	"\vInfoRequest\"\x13\n" +
	"\x11MeshStatusRequest\"\x0f\n" +
	"\rEventsRequest\"\x05\n" +
	"\x03Eof\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"E\n" +
	"\x06Output\x12'\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x0f.vmon.v1.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\x04Exit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x1b\n" +
	"\x06signal\x18\x02 \x01(\x03H\x00R\x06signal\x88\x01\x01B\t\n" +
	"\a_signal\"&\n" +
	"\x05Ready\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId*Z\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTREAM_STDOUT\x10\x01\x12\x11\n" +
	"\rSTREAM_STDERR\x10\x02\x12\x12\n" +
	"\x0eSTREAM_CONSOLE\x10\x032\xbe\v\n" +
	"\x0eSandboxService\x12:\n" +
	"\x06Create\x12\x1d.vmon.v1.CreateSandboxRequest\x1a\x11.vmon.v1.JsonView\x12E\n" +
	"\x04List\x12\x1d.vmon.v1.ListSandboxesRequest\x1a\x1e.vmon.v1.ListSandboxesResponse\x12-\n" +
	"\x03Get\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x126\n" +
	"\x04Stop\x12\x1b.vmon.v1.StopSandboxRequest\x1a\x11.vmon.v1.JsonView\x120\n" +
	"\x06Remove\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x123\n" +
	"\tTerminate\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x12/\n" +
	"\x05Pause\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x120\n" +
	"\x06Resume\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x12:\n" +
	"\x06Extend\x12\x1d.vmon.v1.ExtendSandboxRequest\x1a\x11.vmon.v1.JsonView\x121\n" +
	"\aMetrics\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x121\n" +
	"\x04Logs\x12\x14.vmon.v1.LogsRequest\x1a\x11.vmon.v1.LogChunk0\x01\x12H\n" +
	"\vExecCapture\x12\x1b.vmon.v1.ExecCaptureRequest\x1a\x1c.vmon.v1.ExecCaptureResponse\x123\n" +
	"\x04Exec\x12\x12.vmon.v1.ExecInput\x1a\x13.vmon.v1.ExecOutput(\x010\x01\x124\n" +
	"\x05Shell\x12\x12.vmon.v1.ExecInput\x1a\x13.vmon.v1.ExecOutput(\x010\x01\x124\n" +
	"\x06Attach\x12\x13.vmon.v1.SandboxRef\x1a\x13.vmon.v1.ExecOutput0\x01\x12:\n" +
	"\bFileRead\x12\x18.vmon.v1.FilePathRequest\x1a\x14.vmon.v1.FileContent\x123\n" +
	"\tFileWrite\x12\x19.vmon.v1.FileWriteRequest\x1a\v.vmon.v1.Ok\x125\n" +
	"\n" +
	"FileDelete\x12\x1a.vmon.v1.FileDeleteRequest\x1a\v.vmon.v1.Ok\x127\n" +
	"\bFileList\x12\x18.vmon.v1.FilePathRequest\x1a\x11.vmon.v1.JsonView\x127\n" +
	"\bFileStat\x12\x18.vmon.v1.FilePathRequest\x1a\x11.vmon.v1.JsonView\x124\n" +
	"\n" +
	"NetworkGet\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x12;\n" +
	"\n" +
	"NetworkSet\x12\x1a.vmon.v1.NetworkSetRequest\x1a\x11.vmon.v1.JsonView\x121\n" +
	"\aTunnels\x12\x13.vmon.v1.SandboxRef\x1a\x11.vmon.v1.JsonView\x125\n" +
	"\aMigrate\x12\x17.vmon.v1.MigrateRequest\x1a\x11.vmon.v1.JsonView\x127\n" +
	"\bSnapshot\x12\x18.vmon.v1.SnapshotRequest\x1a\x11.vmon.v1.JsonView\x12;\n" +
	"\n" +
	"SnapshotFs\x12\x1a.vmon.v1.SnapshotFsRequest\x1a\x11.vmon.v1.JsonView2\xc7\x01\n" +
	"\x0fSnapshotService\x12<\n" +
	"\x04List\x12\x1d.vmon.v1.ListSnapshotsRequest\x1a\x15.vmon.v1.SnapshotList\x12=\n" +
	"\aRestore\x12\x1f.vmon.v1.RestoreSnapshotRequest\x1a\x11.vmon.v1.JsonView\x127\n" +
	"\x04Fork\x12\x1c.vmon.v1.ForkSnapshotRequest\x1a\x11.vmon.v1.JsonView2\x9f\x01\n" +
	"\rVolumeService\x128\n" +
	"\x04List\x12\x1b.vmon.v1.ListVolumesRequest\x1a\x13.vmon.v1.VolumeList\x12)\n" +
	"\x06Create\x12\x12.vmon.v1.VolumeRef\x1a\v.vmon.v1.Ok\x12)\n" +
	"\x06Delete\x12\x12.vmon.v1.VolumeRef\x1a\v.vmon.v1.Ok2\x9f\x01\n" +
	"\vPoolService\x124\n" +
	"\x04List\x12\x19.vmon.v1.ListPoolsRequest\x1a\x11.vmon.v1.JsonView\x121\n" +
	"\x03Set\x12\x17.vmon.v1.PoolSetRequest\x1a\x11.vmon.v1.JsonView\x12'\n" +
	"\x06Delete\x12\x10.vmon.v1.PoolRef\x1a\v.vmon.v1.Ok2\xb4\x01\n" +
	"\rSystemService\x12/\n" +
	"\x04Info\x12\x14.vmon.v1.InfoRequest\x1a\x11.vmon.v1.JsonView\x125\n" +
	"\x06Events\x12\x16.vmon.v1.EventsRequest\x1a\x11.vmon.v1.JsonView0\x01\x12;\n" +
	"\n" +
	"MeshStatus\x12\x1a.vmon.v1.MeshStatusRequest\x1a\x11.vmon.v1.JsonViewB/Z-github.com/can1357/vibemon/sdk/go/internal/pbb\x06proto3"

var (
	file_vmon_v1_api_proto_rawDescOnce sync.Once
	file_vmon_v1_api_proto_rawDescData []byte
)

func file_vmon_v1_api_proto_rawDescGZIP() []byte {
	file_vmon_v1_api_proto_rawDescOnce.Do(func() {
		file_vmon_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmon_v1_api_proto_rawDesc), len(file_vmon_v1_api_proto_rawDesc)))
	})
	return file_vmon_v1_api_proto_rawDescData
}

var file_vmon_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vmon_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_vmon_v1_api_proto_goTypes = []any{
	(Stream)(0),                    // 0: vmon.v1.Stream
	(*JsonView)(nil),               // 1: vmon.v1.JsonView
	(*Ok)(nil),                     // 2: vmon.v1.Ok
	(*SandboxRef)(nil),             // 3: vmon.v1.SandboxRef
	(*CreateSandboxRequest)(nil),   // 4: vmon.v1.CreateSandboxRequest
	(*ListSandboxesRequest)(nil),   // 5: vmon.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),  // 6: vmon.v1.ListSandboxesResponse
	(*StopSandboxRequest)(nil),     // 7: vmon.v1.StopSandboxRequest
	(*ExtendSandboxRequest)(nil),   // 8: vmon.v1.ExtendSandboxRequest
	(*LogsRequest)(nil),            // 9: vmon.v1.LogsRequest
	(*LogChunk)(nil),               // 10: vmon.v1.LogChunk
	(*ExecStart)(nil),              // 11: vmon.v1.ExecStart
	(*ExecCaptureRequest)(nil),     // 12: vmon.v1.ExecCaptureRequest
	(*ExecCaptureResponse)(nil),    // 13: vmon.v1.ExecCaptureResponse
	(*ExecInput)(nil),              // 14: vmon.v1.ExecInput
	(*ExecOutput)(nil),             // 15: vmon.v1.ExecOutput
	(*FilePathRequest)(nil),        // 16: vmon.v1.FilePathRequest
	(*FileContent)(nil),            // 17: vmon.v1.FileContent
	(*FileWriteRequest)(nil),       // 18: vmon.v1.FileWriteRequest
	(*FileDeleteRequest)(nil),      // 19: vmon.v1.FileDeleteRequest
	(*StringList)(nil),             // 20: vmon.v1.StringList
	(*NetworkSetRequest)(nil),      // 21: vmon.v1.NetworkSetRequest
	(*MigrateRequest)(nil),         // 22: vmon.v1.MigrateRequest
	(*SnapshotRequest)(nil),        // 23: vmon.v1.SnapshotRequest
	(*SnapshotFsRequest)(nil),      // 24: vmon.v1.SnapshotFsRequest
	(*ListSnapshotsRequest)(nil),   // 25: vmon.v1.ListSnapshotsRequest
	(*SnapshotList)(nil),           // 26: vmon.v1.SnapshotList
	(*RestoreSnapshotRequest)(nil), // 27: vmon.v1.RestoreSnapshotRequest
	(*ForkSnapshotRequest)(nil),    // 28: vmon.v1.ForkSnapshotRequest
	(*ListVolumesRequest)(nil),     // 29: vmon.v1.ListVolumesRequest
	(*VolumeList)(nil),             // 30: vmon.v1.VolumeList
	(*VolumeRef)(nil),              // 31: vmon.v1.VolumeRef
	(*ListPoolsRequest)(nil),       // 32: vmon.v1.ListPoolsRequest
	(*PoolSetRequest)(nil),         // 33: vmon.v1.PoolSetRequest
	(*PoolRef)(nil),                // 34: vmon.v1.PoolRef
	(*InfoRequest)(nil),            // 35: vmon.v1.InfoRequest
	(*MeshStatusRequest)(nil),      // 36: vmon.v1.MeshStatusRequest
	(*EventsRequest)(nil),          // 37: vmon.v1.EventsRequest
	(*Eof)(nil),                    // 38: vmon.v1.Eof
	(*Resize)(nil),                 // 39: vmon.v1.Resize
	(*Output)(nil),                 // 40: vmon.v1.Output
	(*Exit)(nil),                   // 41: vmon.v1.Exit
	(*Ready)(nil),                  // 42: vmon.v1.Ready
	nil,                            // 43: vmon.v1.ExecStart.EnvEntry
}
var file_vmon_v1_api_proto_depIdxs = []int32{
	43, // 0: vmon.v1.ExecStart.env:type_name -> vmon.v1.ExecStart.EnvEntry
	11, // 1: vmon.v1.ExecCaptureRequest.exec:type_name -> vmon.v1.ExecStart
	11, // 2: vmon.v1.ExecInput.start:type_name -> vmon.v1.ExecStart
	38, // 3: vmon.v1.ExecInput.eof:type_name -> vmon.v1.Eof
	39, // 4: vmon.v1.ExecInput.resize:type_name -> vmon.v1.Resize
	40, // 5: vmon.v1.ExecOutput.chunk:type_name -> vmon.v1.Output
	41, // 6: vmon.v1.ExecOutput.exit:type_name -> vmon.v1.Exit
	42, // 7: vmon.v1.ExecOutput.ready:type_name -> vmon.v1.Ready
	20, // 8: vmon.v1.NetworkSetRequest.cidr_allow:type_name -> vmon.v1.StringList
	20, // 9: vmon.v1.NetworkSetRequest.domain_allow:type_name -> vmon.v1.StringList
	0,  // 10: vmon.v1.Output.stream:type_name -> vmon.v1.Stream
	4,  // 11: vmon.v1.SandboxService.Create:input_type -> vmon.v1.CreateSandboxRequest
	5,  // 12: vmon.v1.SandboxService.List:input_type -> vmon.v1.ListSandboxesRequest
	3,  // 13: vmon.v1.SandboxService.Get:input_type -> vmon.v1.SandboxRef
	7,  // 14: vmon.v1.SandboxService.Stop:input_type -> vmon.v1.StopSandboxRequest
	3,  // 15: vmon.v1.SandboxService.Remove:input_type -> vmon.v1.SandboxRef
	3,  // 16: vmon.v1.SandboxService.Terminate:input_type -> vmon.v1.SandboxRef
	3,  // 17: vmon.v1.SandboxService.Pause:input_type -> vmon.v1.SandboxRef
	3,  // 18: vmon.v1.SandboxService.Resume:input_type -> vmon.v1.SandboxRef
	8,  // 19: vmon.v1.SandboxService.Extend:input_type -> vmon.v1.ExtendSandboxRequest
	3,  // 20: vmon.v1.SandboxService.Metrics:input_type -> vmon.v1.SandboxRef
	9,  // 21: vmon.v1.SandboxService.Logs:input_type -> vmon.v1.LogsRequest
	12, // 22: vmon.v1.SandboxService.ExecCapture:input_type -> vmon.v1.ExecCaptureRequest
	14, // 23: vmon.v1.SandboxService.Exec:input_type -> vmon.v1.ExecInput
	14, // 24: vmon.v1.SandboxService.Shell:input_type -> vmon.v1.ExecInput
	3,  // 25: vmon.v1.SandboxService.Attach:input_type -> vmon.v1.SandboxRef
	16, // 26: vmon.v1.SandboxService.FileRead:input_type -> vmon.v1.FilePathRequest
	18, // 27: vmon.v1.SandboxService.FileWrite:input_type -> vmon.v1.FileWriteRequest
	19, // 28: vmon.v1.SandboxService.FileDelete:input_type -> vmon.v1.FileDeleteRequest
	16, // 29: vmon.v1.SandboxService.FileList:input_type -> vmon.v1.FilePathRequest
	16, // 30: vmon.v1.SandboxService.FileStat:input_type -> vmon.v1.FilePathRequest
	3,  // 31: vmon.v1.SandboxService.NetworkGet:input_type -> vmon.v1.SandboxRef
	21, // 32: vmon.v1.SandboxService.NetworkSet:input_type -> vmon.v1.NetworkSetRequest
	3,  // 33: vmon.v1.SandboxService.Tunnels:input_type -> vmon.v1.SandboxRef
	22, // 34: vmon.v1.SandboxService.Migrate:input_type -> vmon.v1.MigrateRequest
	23, // 35: vmon.v1.SandboxService.Snapshot:input_type -> vmon.v1.SnapshotRequest
	24, // 36: vmon.v1.SandboxService.SnapshotFs:input_type -> vmon.v1.SnapshotFsRequest
	25, // 37: vmon.v1.SnapshotService.List:input_type -> vmon.v1.ListSnapshotsRequest
	27, // 38: vmon.v1.SnapshotService.Restore:input_type -> vmon.v1.RestoreSnapshotRequest
	28, // 39: vmon.v1.SnapshotService.Fork:input_type -> vmon.v1.ForkSnapshotRequest
	29, // 40: vmon.v1.VolumeService.List:input_type -> vmon.v1.ListVolumesRequest
	31, // 41: vmon.v1.VolumeService.Create:input_type -> vmon.v1.VolumeRef
	31, // 42: vmon.v1.VolumeService.Delete:input_type -> vmon.v1.VolumeRef
	32, // 43: vmon.v1.PoolService.List:input_type -> vmon.v1.ListPoolsRequest
	33, // 44: vmon.v1.PoolService.Set:input_type -> vmon.v1.PoolSetRequest
	34, // 45: vmon.v1.PoolService.Delete:input_type -> vmon.v1.PoolRef
	35, // 46: vmon.v1.SystemService.Info:input_type -> vmon.v1.InfoRequest
	37, // 47: vmon.v1.SystemService.Events:input_type -> vmon.v1.EventsRequest
	36, // 48: vmon.v1.SystemService.MeshStatus:input_type -> vmon.v1.MeshStatusRequest
	1,  // 49: vmon.v1.SandboxService.Create:output_type -> vmon.v1.JsonView
	6,  // 50: vmon.v1.SandboxService.List:output_type -> vmon.v1.ListSandboxesResponse
	1,  // 51: vmon.v1.SandboxService.Get:output_type -> vmon.v1.JsonView
	1,  // 52: vmon.v1.SandboxService.Stop:output_type -> vmon.v1.JsonView
	1,  // 53: vmon.v1.SandboxService.Remove:output_type -> vmon.v1.JsonView
	1,  // 54: vmon.v1.SandboxService.Terminate:output_type -> vmon.v1.JsonView
	1,  // 55: vmon.v1.SandboxService.Pause:output_type -> vmon.v1.JsonView
	1,  // 56: vmon.v1.SandboxService.Resume:output_type -> vmon.v1.JsonView
	1,  // 57: vmon.v1.SandboxService.Extend:output_type -> vmon.v1.JsonView
	1,  // 58: vmon.v1.SandboxService.Metrics:output_type -> vmon.v1.JsonView
	10, // 59: vmon.v1.SandboxService.Logs:output_type -> vmon.v1.LogChunk
	13, // 60: vmon.v1.SandboxService.ExecCapture:output_type -> vmon.v1.ExecCaptureResponse
	15, // 61: vmon.v1.SandboxService.Exec:output_type -> vmon.v1.ExecOutput
	15, // 62: vmon.v1.SandboxService.Shell:output_type -> vmon.v1.ExecOutput
	15, // 63: vmon.v1.SandboxService.Attach:output_type -> vmon.v1.ExecOutput
	17, // 64: vmon.v1.SandboxService.FileRead:output_type -> vmon.v1.FileContent
	2,  // 65: vmon.v1.SandboxService.FileWrite:output_type -> vmon.v1.Ok
	2,  // 66: vmon.v1.SandboxService.FileDelete:output_type -> vmon.v1.Ok
	1,  // 67: vmon.v1.SandboxService.FileList:output_type -> vmon.v1.JsonView
	1,  // 68: vmon.v1.SandboxService.FileStat:output_type -> vmon.v1.JsonView
	1,  // 69: vmon.v1.SandboxService.NetworkGet:output_type -> vmon.v1.JsonView
	1,  // 70: vmon.v1.SandboxService.NetworkSet:output_type -> vmon.v1.JsonView
	1,  // 71: vmon.v1.SandboxService.Tunnels:output_type -> vmon.v1.JsonView
	1,  // 72: vmon.v1.SandboxService.Migrate:output_type -> vmon.v1.JsonView
	1,  // 73: vmon.v1.SandboxService.Snapshot:output_type -> vmon.v1.JsonView
	1,  // 74: vmon.v1.SandboxService.SnapshotFs:output_type -> vmon.v1.JsonView
	26, // 75: vmon.v1.SnapshotService.List:output_type -> vmon.v1.SnapshotList
	1,  // 76: vmon.v1.SnapshotService.Restore:output_type -> vmon.v1.JsonView
	1,  // 77: vmon.v1.SnapshotService.Fork:output_type -> vmon.v1.JsonView
	30, // 78: vmon.v1.VolumeService.List:output_type -> vmon.v1.VolumeList
	2,  // 79: vmon.v1.VolumeService.Create:output_type -> vmon.v1.Ok
	2,  // 80: vmon.v1.VolumeService.Delete:output_type -> vmon.v1.Ok
	1,  // 81: vmon.v1.PoolService.List:output_type -> vmon.v1.JsonView
	1,  // 82: vmon.v1.PoolService.Set:output_type -> vmon.v1.JsonView
	2,  // 83: vmon.v1.PoolService.Delete:output_type -> vmon.v1.Ok
	1,  // 84: vmon.v1.SystemService.Info:output_type -> vmon.v1.JsonView
	1,  // 85: vmon.v1.SystemService.Events:output_type -> vmon.v1.JsonView
	1,  // 86: vmon.v1.SystemService.MeshStatus:output_type -> vmon.v1.JsonView
	49, // [49:87] is the sub-list for method output_type
	11, // [11:49] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_vmon_v1_api_proto_init() }
func file_vmon_v1_api_proto_init() {
	if File_vmon_v1_api_proto != nil {
		return
	}
	file_vmon_v1_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_vmon_v1_api_proto_msgTypes[8].OneofWrappers = []any{}
	file_vmon_v1_api_proto_msgTypes[10].OneofWrappers = []any{}
	file_vmon_v1_api_proto_msgTypes[12].OneofWrappers = []any{}
	file_vmon_v1_api_proto_msgTypes[13].OneofWrappers = []any{
		(*ExecInput_Start)(nil),
		(*ExecInput_ShellParamsJson)(nil),
		(*ExecInput_Stdin)(nil),
		(*ExecInput_Eof)(nil),
		(*ExecInput_Resize)(nil),
	}
	file_vmon_v1_api_proto_msgTypes[14].OneofWrappers = []any{
		(*ExecOutput_Chunk)(nil),
		(*ExecOutput_Exit)(nil),
		(*ExecOutput_Ready)(nil),
	}
	file_vmon_v1_api_proto_msgTypes[20].OneofWrappers = []any{}
	file_vmon_v1_api_proto_msgTypes[22].OneofWrappers = []any{}
	file_vmon_v1_api_proto_msgTypes[23].OneofWrappers = []any{}
	file_vmon_v1_api_proto_msgTypes[40].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmon_v1_api_proto_rawDesc), len(file_vmon_v1_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_vmon_v1_api_proto_goTypes,
		DependencyIndexes: file_vmon_v1_api_proto_depIdxs,
		EnumInfos:         file_vmon_v1_api_proto_enumTypes,
		MessageInfos:      file_vmon_v1_api_proto_msgTypes,
	}.Build()
	File_vmon_v1_api_proto = out.File
	file_vmon_v1_api_proto_goTypes = nil
	file_vmon_v1_api_proto_depIdxs = nil
}
