// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vmon/v1/api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_Create_FullMethodName      = "/vmon.v1.SandboxService/Create"
	SandboxService_List_FullMethodName        = "/vmon.v1.SandboxService/List"
	SandboxService_Get_FullMethodName         = "/vmon.v1.SandboxService/Get"
	SandboxService_Stop_FullMethodName        = "/vmon.v1.SandboxService/Stop"
	SandboxService_Remove_FullMethodName      = "/vmon.v1.SandboxService/Remove"
	SandboxService_Terminate_FullMethodName   = "/vmon.v1.SandboxService/Terminate"
	SandboxService_Pause_FullMethodName       = "/vmon.v1.SandboxService/Pause"
	SandboxService_Resume_FullMethodName      = "/vmon.v1.SandboxService/Resume"
	SandboxService_Extend_FullMethodName      = "/vmon.v1.SandboxService/Extend"
	SandboxService_Metrics_FullMethodName     = "/vmon.v1.SandboxService/Metrics"
	SandboxService_Logs_FullMethodName        = "/vmon.v1.SandboxService/Logs"
	SandboxService_ExecCapture_FullMethodName = "/vmon.v1.SandboxService/ExecCapture"
	SandboxService_Exec_FullMethodName        = "/vmon.v1.SandboxService/Exec"
	SandboxService_Shell_FullMethodName       = "/vmon.v1.SandboxService/Shell"
	SandboxService_Attach_FullMethodName      = "/vmon.v1.SandboxService/Attach"
	SandboxService_FileRead_FullMethodName    = "/vmon.v1.SandboxService/FileRead"
	SandboxService_FileWrite_FullMethodName   = "/vmon.v1.SandboxService/FileWrite"
	SandboxService_FileDelete_FullMethodName  = "/vmon.v1.SandboxService/FileDelete"
	SandboxService_FileList_FullMethodName    = "/vmon.v1.SandboxService/FileList"
	SandboxService_FileStat_FullMethodName    = "/vmon.v1.SandboxService/FileStat"
	SandboxService_NetworkGet_FullMethodName  = "/vmon.v1.SandboxService/NetworkGet"
	SandboxService_NetworkSet_FullMethodName  = "/vmon.v1.SandboxService/NetworkSet"
	SandboxService_Tunnels_FullMethodName     = "/vmon.v1.SandboxService/Tunnels"
	SandboxService_Migrate_FullMethodName     = "/vmon.v1.SandboxService/Migrate"
	SandboxService_Snapshot_FullMethodName    = "/vmon.v1.SandboxService/Snapshot"
	SandboxService_SnapshotFs_FullMethodName  = "/vmon.v1.SandboxService/SnapshotFs"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxService provides RPCs to manage microVM sandboxes, perform file operations,
// stream logs, manage networks, and execute interactive processes.
type SandboxServiceClient interface {
	// Creates a new microVM sandbox instance.
	//
	// Replaces: POST /v1/sandboxes
	// Errors:
	//   - `invalid` (INVALID_ARGUMENT): The create spec is invalid or malformed.
	//   - `busy` (ABORTED): Required resources are locked.
	//   - `engine` (UNAVAILABLE): Hypervisor allocation or creation failed.
	Create(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Lists all registered microVM sandboxes, optionally filtered by tags.
	//
	// Replaces: GET /v1/sandboxes
	List(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	// Retrieves the current state, metadata, and status of a specific microVM sandbox.
	//
	// Replaces: GET /v1/sandboxes/{id}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Get(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Gracefully stops a running sandbox microVM.
	// Sends a shutdown signal to the guest OS. If it fails to exit within a grace period,
	// it may be forcefully terminated depending on configuration.
	//
	// Replaces: POST /v1/sandboxes/{id}/stop
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is already stopped.
	Stop(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Stops (if running) and removes a sandbox from the registry, freeing all non-persistent resources.
	//
	// Replaces: DELETE /v1/sandboxes/{id}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Remove(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Immediately terminates a sandbox microVM hypervisor process without graceful shutdown.
	// Equivalent to pulling the power plug.
	//
	// Replaces: POST /v1/sandboxes/{id}/terminate
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Terminate(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Pauses the execution of all vCPUs in the sandbox.
	// CPU threads are quiesced via signal (Linux) or hypervisor callback (macOS/HVF).
	//
	// Replaces: POST /v1/sandboxes/{id}/pause
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	Pause(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Resumes vCPU execution for a paused sandbox.
	//
	// Replaces: POST /v1/sandboxes/{id}/resume
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not in a paused state.
	Resume(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Extends the sandbox's remaining wall-clock time-to-live (TTL) by the specified duration.
	//
	// Replaces: POST /v1/sandboxes/{id}/extend
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Extend(ctx context.Context, in *ExtendSandboxRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Retrieves real-time performance and utilization metrics for the microVM.
	// Includes CPU utilization, memory footprint, virtio block/net throughput, and guest metrics.
	//
	// Replaces: GET /v1/sandboxes/{id}/metrics
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Metrics(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Streams the console log output of the microVM.
	// Supports streaming historical logs (via `tail`) and real-time output (via `follow`).
	//
	// Replaces: GET /v1/sandboxes/{id}/logs
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	// Executes a non-interactive command inside the guest via the guest agent and captures
	// its complete exit status, stdout, and stderr.
	//
	// Replaces: POST /v1/sandboxes/{id}/exec
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running or guest agent is unreachable.
	//   - `invalid` (INVALID_ARGUMENT): Invalid command or arguments.
	ExecCapture(ctx context.Context, in *ExecCaptureRequest, opts ...grpc.CallOption) (*ExecCaptureResponse, error)
	// Opens a bidirectional, interactive execution stream inside the guest via the guest agent.
	// Supports PTY/TTY allocation, real-time stdin write, resize, EOF signaling, and exit status streaming.
	// The first `ExecInput` message sent MUST contain the `ExecStart` payload.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running or guest agent is unreachable.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error)
	// Opens an interactive shell session inside the guest.
	// The first `ExecInput` message sent MUST contain the `shell_params_json` payload.
	// The server emits a `Ready` frame containing the resolved sandbox ID before streaming I/O.
	//
	// Replaces: GET /v1/shell
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error)
	// Attaches a read-only stream to the microVM serial console, forwarding guest kernel output and boot logs.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Attach(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error)
	// Reads the complete contents of a file inside the guest sandbox filesystem.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified file does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileRead(ctx context.Context, in *FilePathRequest, opts ...grpc.CallOption) (*FileContent, error)
	// Writes or overwrites a file inside the guest sandbox filesystem.
	// Creates parent directories if they do not exist.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*Ok, error)
	// Deletes a file or directory inside the guest sandbox filesystem.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified file/directory does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*Ok, error)
	// Lists files and directories within a given directory inside the guest sandbox.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified path does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileList(ctx context.Context, in *FilePathRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Performs a metadata query (stat) on a file inside the guest sandbox (size, type, permissions, times).
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified file does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileStat(ctx context.Context, in *FilePathRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Retrieves the active network configuration, interfaces, and routing for the sandbox.
	//
	// Replaces: GET /v1/sandboxes/{id}/network
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	NetworkGet(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Updates the network access controls, allowed CIDRs, and allowed domains for the sandbox.
	//
	// Replaces: PUT /v1/sandboxes/{id}/network
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Invalid network rules or CIDR formats.
	NetworkSet(ctx context.Context, in *NetworkSetRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Retrieves active network tunnels and port-forwardings mapped to the sandbox.
	//
	// Replaces: GET /v1/sandboxes/{id}/tunnels
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Tunnels(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error)
	// Initiates state migration of the sandbox to a target destination or host.
	//
	// Replaces: POST /v1/sandboxes/{id}/migrate
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Target destination is invalid or unreachable.
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Captures a snapshot of the sandbox's memory, register, and device state.
	//
	// Replaces: POST /v1/sandboxes/{id}/snapshot
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not currently running.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Triggers a filesystem freeze and creates a filesystem-level snapshot on disk.
	//
	// Replaces: POST /v1/sandboxes/{id}/snapshot-fs
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	SnapshotFs(ctx context.Context, in *SnapshotFsRequest, opts ...grpc.CallOption) (*JsonView, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) Create(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) List(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Get(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Stop(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Remove(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Terminate(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Pause(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Resume(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Extend(ctx context.Context, in *ExtendSandboxRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Extend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Metrics(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[0], SandboxService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_LogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *sandboxServiceClient) ExecCapture(ctx context.Context, in *ExecCaptureRequest, opts ...grpc.CallOption) (*ExecCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecCaptureResponse)
	err := c.cc.Invoke(ctx, SandboxService_ExecCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[1], SandboxService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecInput, ExecOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ExecClient = grpc.BidiStreamingClient[ExecInput, ExecOutput]

func (c *sandboxServiceClient) Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[2], SandboxService_Shell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecInput, ExecOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ShellClient = grpc.BidiStreamingClient[ExecInput, ExecOutput]

func (c *sandboxServiceClient) Attach(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[3], SandboxService_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SandboxRef, ExecOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_AttachClient = grpc.ServerStreamingClient[ExecOutput]

func (c *sandboxServiceClient) FileRead(ctx context.Context, in *FilePathRequest, opts ...grpc.CallOption) (*FileContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileContent)
	err := c.cc.Invoke(ctx, SandboxService_FileRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, SandboxService_FileWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, SandboxService_FileDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) FileList(ctx context.Context, in *FilePathRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_FileList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) FileStat(ctx context.Context, in *FilePathRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_FileStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) NetworkGet(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_NetworkGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) NetworkSet(ctx context.Context, in *NetworkSetRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_NetworkSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Tunnels(ctx context.Context, in *SandboxRef, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Tunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Migrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SnapshotFs(ctx context.Context, in *SnapshotFsRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SandboxService_SnapshotFs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// SandboxService provides RPCs to manage microVM sandboxes, perform file operations,
// stream logs, manage networks, and execute interactive processes.
type SandboxServiceServer interface {
	// Creates a new microVM sandbox instance.
	//
	// Replaces: POST /v1/sandboxes
	// Errors:
	//   - `invalid` (INVALID_ARGUMENT): The create spec is invalid or malformed.
	//   - `busy` (ABORTED): Required resources are locked.
	//   - `engine` (UNAVAILABLE): Hypervisor allocation or creation failed.
	Create(context.Context, *CreateSandboxRequest) (*JsonView, error)
	// Lists all registered microVM sandboxes, optionally filtered by tags.
	//
	// Replaces: GET /v1/sandboxes
	List(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	// Retrieves the current state, metadata, and status of a specific microVM sandbox.
	//
	// Replaces: GET /v1/sandboxes/{id}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Get(context.Context, *SandboxRef) (*JsonView, error)
	// Gracefully stops a running sandbox microVM.
	// Sends a shutdown signal to the guest OS. If it fails to exit within a grace period,
	// it may be forcefully terminated depending on configuration.
	//
	// Replaces: POST /v1/sandboxes/{id}/stop
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is already stopped.
	Stop(context.Context, *StopSandboxRequest) (*JsonView, error)
	// Stops (if running) and removes a sandbox from the registry, freeing all non-persistent resources.
	//
	// Replaces: DELETE /v1/sandboxes/{id}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Remove(context.Context, *SandboxRef) (*JsonView, error)
	// Immediately terminates a sandbox microVM hypervisor process without graceful shutdown.
	// Equivalent to pulling the power plug.
	//
	// Replaces: POST /v1/sandboxes/{id}/terminate
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Terminate(context.Context, *SandboxRef) (*JsonView, error)
	// Pauses the execution of all vCPUs in the sandbox.
	// CPU threads are quiesced via signal (Linux) or hypervisor callback (macOS/HVF).
	//
	// Replaces: POST /v1/sandboxes/{id}/pause
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	Pause(context.Context, *SandboxRef) (*JsonView, error)
	// Resumes vCPU execution for a paused sandbox.
	//
	// Replaces: POST /v1/sandboxes/{id}/resume
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not in a paused state.
	Resume(context.Context, *SandboxRef) (*JsonView, error)
	// Extends the sandbox's remaining wall-clock time-to-live (TTL) by the specified duration.
	//
	// Replaces: POST /v1/sandboxes/{id}/extend
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Extend(context.Context, *ExtendSandboxRequest) (*JsonView, error)
	// Retrieves real-time performance and utilization metrics for the microVM.
	// Includes CPU utilization, memory footprint, virtio block/net throughput, and guest metrics.
	//
	// Replaces: GET /v1/sandboxes/{id}/metrics
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Metrics(context.Context, *SandboxRef) (*JsonView, error)
	// Streams the console log output of the microVM.
	// Supports streaming historical logs (via `tail`) and real-time output (via `follow`).
	//
	// Replaces: GET /v1/sandboxes/{id}/logs
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	// Executes a non-interactive command inside the guest via the guest agent and captures
	// its complete exit status, stdout, and stderr.
	//
	// Replaces: POST /v1/sandboxes/{id}/exec
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running or guest agent is unreachable.
	//   - `invalid` (INVALID_ARGUMENT): Invalid command or arguments.
	ExecCapture(context.Context, *ExecCaptureRequest) (*ExecCaptureResponse, error)
	// Opens a bidirectional, interactive execution stream inside the guest via the guest agent.
	// Supports PTY/TTY allocation, real-time stdin write, resize, EOF signaling, and exit status streaming.
	// The first `ExecInput` message sent MUST contain the `ExecStart` payload.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running or guest agent is unreachable.
	Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error
	// Opens an interactive shell session inside the guest.
	// The first `ExecInput` message sent MUST contain the `shell_params_json` payload.
	// The server emits a `Ready` frame containing the resolved sandbox ID before streaming I/O.
	//
	// Replaces: GET /v1/shell
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	Shell(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error
	// Attaches a read-only stream to the microVM serial console, forwarding guest kernel output and boot logs.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Attach(*SandboxRef, grpc.ServerStreamingServer[ExecOutput]) error
	// Reads the complete contents of a file inside the guest sandbox filesystem.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified file does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileRead(context.Context, *FilePathRequest) (*FileContent, error)
	// Writes or overwrites a file inside the guest sandbox filesystem.
	// Creates parent directories if they do not exist.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileWrite(context.Context, *FileWriteRequest) (*Ok, error)
	// Deletes a file or directory inside the guest sandbox filesystem.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified file/directory does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileDelete(context.Context, *FileDeleteRequest) (*Ok, error)
	// Lists files and directories within a given directory inside the guest sandbox.
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified path does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileList(context.Context, *FilePathRequest) (*JsonView, error)
	// Performs a metadata query (stat) on a file inside the guest sandbox (size, type, permissions, times).
	//
	// Errors:
	//   - `not_found` (NOT_FOUND): The sandbox or the specified file does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	FileStat(context.Context, *FilePathRequest) (*JsonView, error)
	// Retrieves the active network configuration, interfaces, and routing for the sandbox.
	//
	// Replaces: GET /v1/sandboxes/{id}/network
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	NetworkGet(context.Context, *SandboxRef) (*JsonView, error)
	// Updates the network access controls, allowed CIDRs, and allowed domains for the sandbox.
	//
	// Replaces: PUT /v1/sandboxes/{id}/network
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Invalid network rules or CIDR formats.
	NetworkSet(context.Context, *NetworkSetRequest) (*JsonView, error)
	// Retrieves active network tunnels and port-forwardings mapped to the sandbox.
	//
	// Replaces: GET /v1/sandboxes/{id}/tunnels
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	Tunnels(context.Context, *SandboxRef) (*JsonView, error)
	// Initiates state migration of the sandbox to a target destination or host.
	//
	// Replaces: POST /v1/sandboxes/{id}/migrate
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Target destination is invalid or unreachable.
	Migrate(context.Context, *MigrateRequest) (*JsonView, error)
	// Captures a snapshot of the sandbox's memory, register, and device state.
	//
	// Replaces: POST /v1/sandboxes/{id}/snapshot
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not currently running.
	Snapshot(context.Context, *SnapshotRequest) (*JsonView, error)
	// Triggers a filesystem freeze and creates a filesystem-level snapshot on disk.
	//
	// Replaces: POST /v1/sandboxes/{id}/snapshot-fs
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified sandbox ID does not exist.
	//   - `not_running` (FAILED_PRECONDITION): The sandbox is not running.
	SnapshotFs(context.Context, *SnapshotFsRequest) (*JsonView, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) Create(context.Context, *CreateSandboxRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSandboxServiceServer) List(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSandboxServiceServer) Get(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSandboxServiceServer) Stop(context.Context, *StopSandboxRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedSandboxServiceServer) Remove(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedSandboxServiceServer) Terminate(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedSandboxServiceServer) Pause(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedSandboxServiceServer) Resume(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSandboxServiceServer) Extend(context.Context, *ExtendSandboxRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Extend not implemented")
}
func (UnimplementedSandboxServiceServer) Metrics(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedSandboxServiceServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedSandboxServiceServer) ExecCapture(context.Context, *ExecCaptureRequest) (*ExecCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecCapture not implemented")
}
func (UnimplementedSandboxServiceServer) Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxServiceServer) Shell(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method Shell not implemented")
}
func (UnimplementedSandboxServiceServer) Attach(*SandboxRef, grpc.ServerStreamingServer[ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedSandboxServiceServer) FileRead(context.Context, *FilePathRequest) (*FileContent, error) {
	return nil, status.Error(codes.Unimplemented, "method FileRead not implemented")
}
func (UnimplementedSandboxServiceServer) FileWrite(context.Context, *FileWriteRequest) (*Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method FileWrite not implemented")
}
func (UnimplementedSandboxServiceServer) FileDelete(context.Context, *FileDeleteRequest) (*Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method FileDelete not implemented")
}
func (UnimplementedSandboxServiceServer) FileList(context.Context, *FilePathRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method FileList not implemented")
}
func (UnimplementedSandboxServiceServer) FileStat(context.Context, *FilePathRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method FileStat not implemented")
}
func (UnimplementedSandboxServiceServer) NetworkGet(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method NetworkGet not implemented")
}
func (UnimplementedSandboxServiceServer) NetworkSet(context.Context, *NetworkSetRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method NetworkSet not implemented")
}
func (UnimplementedSandboxServiceServer) Tunnels(context.Context, *SandboxRef) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Tunnels not implemented")
}
func (UnimplementedSandboxServiceServer) Migrate(context.Context, *MigrateRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedSandboxServiceServer) Snapshot(context.Context, *SnapshotRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedSandboxServiceServer) SnapshotFs(context.Context, *SnapshotFsRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotFs not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Create(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).List(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Get(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Stop(ctx, req.(*StopSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Remove(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Terminate(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Pause(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Resume(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Extend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Extend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Extend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Extend(ctx, req.(*ExtendSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Metrics(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_LogsServer = grpc.ServerStreamingServer[LogChunk]

func _SandboxService_ExecCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ExecCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ExecCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ExecCapture(ctx, req.(*ExecCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxServiceServer).Exec(&grpc.GenericServerStream[ExecInput, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ExecServer = grpc.BidiStreamingServer[ExecInput, ExecOutput]

func _SandboxService_Shell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxServiceServer).Shell(&grpc.GenericServerStream[ExecInput, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_ShellServer = grpc.BidiStreamingServer[ExecInput, ExecOutput]

func _SandboxService_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SandboxRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).Attach(m, &grpc.GenericServerStream[SandboxRef, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_AttachServer = grpc.ServerStreamingServer[ExecOutput]

func _SandboxService_FileRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).FileRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_FileRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).FileRead(ctx, req.(*FilePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_FileWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).FileWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_FileWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).FileWrite(ctx, req.(*FileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_FileDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).FileDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_FileDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).FileDelete(ctx, req.(*FileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_FileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).FileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_FileList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).FileList(ctx, req.(*FilePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_FileStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).FileStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_FileStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).FileStat(ctx, req.(*FilePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_NetworkGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).NetworkGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_NetworkGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).NetworkGet(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_NetworkSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).NetworkSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_NetworkSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).NetworkSet(ctx, req.(*NetworkSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Tunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Tunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Tunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Tunnels(ctx, req.(*SandboxRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SnapshotFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotFsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SnapshotFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SnapshotFs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SnapshotFs(ctx, req.(*SnapshotFsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmon.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SandboxService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SandboxService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SandboxService_Get_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _SandboxService_Stop_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _SandboxService_Remove_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _SandboxService_Terminate_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _SandboxService_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _SandboxService_Resume_Handler,
		},
		{
			MethodName: "Extend",
			Handler:    _SandboxService_Extend_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _SandboxService_Metrics_Handler,
		},
		{
			MethodName: "ExecCapture",
			Handler:    _SandboxService_ExecCapture_Handler,
		},
		{
			MethodName: "FileRead",
			Handler:    _SandboxService_FileRead_Handler,
		},
		{
			MethodName: "FileWrite",
			Handler:    _SandboxService_FileWrite_Handler,
		},
		{
			MethodName: "FileDelete",
			Handler:    _SandboxService_FileDelete_Handler,
		},
		{
			MethodName: "FileList",
			Handler:    _SandboxService_FileList_Handler,
		},
		{
			MethodName: "FileStat",
			Handler:    _SandboxService_FileStat_Handler,
		},
		{
			MethodName: "NetworkGet",
			Handler:    _SandboxService_NetworkGet_Handler,
		},
		{
			MethodName: "NetworkSet",
			Handler:    _SandboxService_NetworkSet_Handler,
		},
		{
			MethodName: "Tunnels",
			Handler:    _SandboxService_Tunnels_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _SandboxService_Migrate_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _SandboxService_Snapshot_Handler,
		},
		{
			MethodName: "SnapshotFs",
			Handler:    _SandboxService_SnapshotFs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _SandboxService_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _SandboxService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Shell",
			Handler:       _SandboxService_Shell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Attach",
			Handler:       _SandboxService_Attach_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vmon/v1/api.proto",
}

const (
	SnapshotService_List_FullMethodName    = "/vmon.v1.SnapshotService/List"
	SnapshotService_Restore_FullMethodName = "/vmon.v1.SnapshotService/Restore"
	SnapshotService_Fork_FullMethodName    = "/vmon.v1.SnapshotService/Fork"
)

// SnapshotServiceClient is the client API for SnapshotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotService manages saved microVM snapshots, enabling restorations and high-density forks.
type SnapshotServiceClient interface {
	// Lists all snapshots currently registered in the engine.
	//
	// Replaces: GET /v1/snapshots
	List(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*SnapshotList, error)
	// Restores a microVM sandbox instance from a previously captured snapshot.
	//
	// Replaces: POST /v1/snapshots/{name}/restore
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified snapshot name does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Invalid configuration parameters.
	Restore(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Rapidly forks one or more new sandbox instances from an existing snapshot.
	// Under the hood, this utilizes copy-on-write sharing for high density and instant startup.
	//
	// Replaces: POST /v1/snapshots/{name}/fork
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified snapshot name does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Invalid count or target configuration.
	Fork(ctx context.Context, in *ForkSnapshotRequest, opts ...grpc.CallOption) (*JsonView, error)
}

type snapshotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotServiceClient(cc grpc.ClientConnInterface) SnapshotServiceClient {
	return &snapshotServiceClient{cc}
}

func (c *snapshotServiceClient) List(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*SnapshotList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotList)
	err := c.cc.Invoke(ctx, SnapshotService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) Restore(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SnapshotService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) Fork(ctx context.Context, in *ForkSnapshotRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SnapshotService_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotServiceServer is the server API for SnapshotService service.
// All implementations must embed UnimplementedSnapshotServiceServer
// for forward compatibility.
//
// SnapshotService manages saved microVM snapshots, enabling restorations and high-density forks.
type SnapshotServiceServer interface {
	// Lists all snapshots currently registered in the engine.
	//
	// Replaces: GET /v1/snapshots
	List(context.Context, *ListSnapshotsRequest) (*SnapshotList, error)
	// Restores a microVM sandbox instance from a previously captured snapshot.
	//
	// Replaces: POST /v1/snapshots/{name}/restore
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified snapshot name does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Invalid configuration parameters.
	Restore(context.Context, *RestoreSnapshotRequest) (*JsonView, error)
	// Rapidly forks one or more new sandbox instances from an existing snapshot.
	// Under the hood, this utilizes copy-on-write sharing for high density and instant startup.
	//
	// Replaces: POST /v1/snapshots/{name}/fork
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified snapshot name does not exist.
	//   - `invalid` (INVALID_ARGUMENT): Invalid count or target configuration.
	Fork(context.Context, *ForkSnapshotRequest) (*JsonView, error)
	mustEmbedUnimplementedSnapshotServiceServer()
}

// UnimplementedSnapshotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotServiceServer struct{}

func (UnimplementedSnapshotServiceServer) List(context.Context, *ListSnapshotsRequest) (*SnapshotList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSnapshotServiceServer) Restore(context.Context, *RestoreSnapshotRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedSnapshotServiceServer) Fork(context.Context, *ForkSnapshotRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedSnapshotServiceServer) mustEmbedUnimplementedSnapshotServiceServer() {}
func (UnimplementedSnapshotServiceServer) testEmbeddedByValue()                         {}

// UnsafeSnapshotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotServiceServer will
// result in compilation errors.
type UnsafeSnapshotServiceServer interface {
	mustEmbedUnimplementedSnapshotServiceServer()
}

func RegisterSnapshotServiceServer(s grpc.ServiceRegistrar, srv SnapshotServiceServer) {
	// If the following call panics, it indicates UnimplementedSnapshotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotService_ServiceDesc, srv)
}

func _SnapshotService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).List(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).Restore(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).Fork(ctx, req.(*ForkSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotService_ServiceDesc is the grpc.ServiceDesc for SnapshotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmon.v1.SnapshotService",
	HandlerType: (*SnapshotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SnapshotService_List_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _SnapshotService_Restore_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _SnapshotService_Fork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmon/v1/api.proto",
}

const (
	VolumeService_List_FullMethodName   = "/vmon.v1.VolumeService/List"
	VolumeService_Create_FullMethodName = "/vmon.v1.VolumeService/Create"
	VolumeService_Delete_FullMethodName = "/vmon.v1.VolumeService/Delete"
)

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VolumeService provides RPCs for managing persistent block storage volumes.
type VolumeServiceClient interface {
	// Lists all persistent volumes currently registered in the engine registry.
	//
	// Replaces: GET /v1/volumes
	List(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*VolumeList, error)
	// Creates a new persistent block storage volume.
	//
	// Replaces: POST /v1/volumes
	// Errors:
	//   - `invalid` (INVALID_ARGUMENT): Invalid volume name, size, or parameters.
	//   - `busy` (ABORTED): Volume with the same name already exists.
	Create(ctx context.Context, in *VolumeRef, opts ...grpc.CallOption) (*Ok, error)
	// Deletes a persistent block storage volume, permanently freeing its underlying disk storage.
	//
	// Replaces: DELETE /v1/volumes/{name}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified volume does not exist.
	//   - `busy` (ABORTED): The volume is currently attached to a sandbox and cannot be deleted.
	Delete(ctx context.Context, in *VolumeRef, opts ...grpc.CallOption) (*Ok, error)
}

type volumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeServiceClient(cc grpc.ClientConnInterface) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) List(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*VolumeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeList)
	err := c.cc.Invoke(ctx, VolumeService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Create(ctx context.Context, in *VolumeRef, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, VolumeService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Delete(ctx context.Context, in *VolumeRef, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, VolumeService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeServiceServer is the server API for VolumeService service.
// All implementations must embed UnimplementedVolumeServiceServer
// for forward compatibility.
//
// VolumeService provides RPCs for managing persistent block storage volumes.
type VolumeServiceServer interface {
	// Lists all persistent volumes currently registered in the engine registry.
	//
	// Replaces: GET /v1/volumes
	List(context.Context, *ListVolumesRequest) (*VolumeList, error)
	// Creates a new persistent block storage volume.
	//
	// Replaces: POST /v1/volumes
	// Errors:
	//   - `invalid` (INVALID_ARGUMENT): Invalid volume name, size, or parameters.
	//   - `busy` (ABORTED): Volume with the same name already exists.
	Create(context.Context, *VolumeRef) (*Ok, error)
	// Deletes a persistent block storage volume, permanently freeing its underlying disk storage.
	//
	// Replaces: DELETE /v1/volumes/{name}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified volume does not exist.
	//   - `busy` (ABORTED): The volume is currently attached to a sandbox and cannot be deleted.
	Delete(context.Context, *VolumeRef) (*Ok, error)
	mustEmbedUnimplementedVolumeServiceServer()
}

// UnimplementedVolumeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeServiceServer struct{}

func (UnimplementedVolumeServiceServer) List(context.Context, *ListVolumesRequest) (*VolumeList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVolumeServiceServer) Create(context.Context, *VolumeRef) (*Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVolumeServiceServer) Delete(context.Context, *VolumeRef) (*Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVolumeServiceServer) mustEmbedUnimplementedVolumeServiceServer() {}
func (UnimplementedVolumeServiceServer) testEmbeddedByValue()                       {}

// UnsafeVolumeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeServiceServer will
// result in compilation errors.
type UnsafeVolumeServiceServer interface {
	mustEmbedUnimplementedVolumeServiceServer()
}

func RegisterVolumeServiceServer(s grpc.ServiceRegistrar, srv VolumeServiceServer) {
	// If the following call panics, it indicates UnimplementedVolumeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumeService_ServiceDesc, srv)
}

func _VolumeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).List(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Create(ctx, req.(*VolumeRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Delete(ctx, req.(*VolumeRef))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumeService_ServiceDesc is the grpc.ServiceDesc for VolumeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmon.v1.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _VolumeService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VolumeService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VolumeService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmon/v1/api.proto",
}

const (
	PoolService_List_FullMethodName   = "/vmon.v1.PoolService/List"
	PoolService_Set_FullMethodName    = "/vmon.v1.PoolService/Set"
	PoolService_Delete_FullMethodName = "/vmon.v1.PoolService/Delete"
)

// PoolServiceClient is the client API for PoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PoolService manages warm pools of standby microVMs to eliminate cold-start latency.
type PoolServiceClient interface {
	// Lists configured warm pools and their standby microVM counts.
	//
	// Replaces: GET /v1/pools
	List(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Creates or updates a warm pool configuration, adjusting the standby target size.
	//
	// Replaces: PUT /v1/pools/{reference}
	// Errors:
	//   - `invalid` (INVALID_ARGUMENT): Invalid pool definition or size.
	Set(ctx context.Context, in *PoolSetRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Deletes a warm pool and tears down all pre-warmed standby sandboxes within it.
	//
	// Replaces: DELETE /v1/pools/{reference}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified pool reference does not exist.
	Delete(ctx context.Context, in *PoolRef, opts ...grpc.CallOption) (*Ok, error)
}

type poolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolServiceClient(cc grpc.ClientConnInterface) PoolServiceClient {
	return &poolServiceClient{cc}
}

func (c *poolServiceClient) List(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, PoolService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) Set(ctx context.Context, in *PoolSetRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, PoolService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) Delete(ctx context.Context, in *PoolRef, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, PoolService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolServiceServer is the server API for PoolService service.
// All implementations must embed UnimplementedPoolServiceServer
// for forward compatibility.
//
// PoolService manages warm pools of standby microVMs to eliminate cold-start latency.
type PoolServiceServer interface {
	// Lists configured warm pools and their standby microVM counts.
	//
	// Replaces: GET /v1/pools
	List(context.Context, *ListPoolsRequest) (*JsonView, error)
	// Creates or updates a warm pool configuration, adjusting the standby target size.
	//
	// Replaces: PUT /v1/pools/{reference}
	// Errors:
	//   - `invalid` (INVALID_ARGUMENT): Invalid pool definition or size.
	Set(context.Context, *PoolSetRequest) (*JsonView, error)
	// Deletes a warm pool and tears down all pre-warmed standby sandboxes within it.
	//
	// Replaces: DELETE /v1/pools/{reference}
	// Errors:
	//   - `not_found` (NOT_FOUND): The specified pool reference does not exist.
	Delete(context.Context, *PoolRef) (*Ok, error)
	mustEmbedUnimplementedPoolServiceServer()
}

// UnimplementedPoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolServiceServer struct{}

func (UnimplementedPoolServiceServer) List(context.Context, *ListPoolsRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPoolServiceServer) Set(context.Context, *PoolSetRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedPoolServiceServer) Delete(context.Context, *PoolRef) (*Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPoolServiceServer) mustEmbedUnimplementedPoolServiceServer() {}
func (UnimplementedPoolServiceServer) testEmbeddedByValue()                     {}

// UnsafePoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolServiceServer will
// result in compilation errors.
type UnsafePoolServiceServer interface {
	mustEmbedUnimplementedPoolServiceServer()
}

func RegisterPoolServiceServer(s grpc.ServiceRegistrar, srv PoolServiceServer) {
	// If the following call panics, it indicates UnimplementedPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolService_ServiceDesc, srv)
}

func _PoolService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).List(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).Set(ctx, req.(*PoolSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).Delete(ctx, req.(*PoolRef))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolService_ServiceDesc is the grpc.ServiceDesc for PoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmon.v1.PoolService",
	HandlerType: (*PoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PoolService_List_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _PoolService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PoolService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmon/v1/api.proto",
}

const (
	SystemService_Info_FullMethodName       = "/vmon.v1.SystemService/Info"
	SystemService_Events_FullMethodName     = "/vmon.v1.SystemService/Events"
	SystemService_MeshStatus_FullMethodName = "/vmon.v1.SystemService/MeshStatus"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SystemService provides administrative queries and streams engine-wide event feeds.
type SystemServiceClient interface {
	// Retrieves general status, version, capabilities, and system metrics from the host engine.
	//
	// Replaces: GET /v1/info
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*JsonView, error)
	// Streams real-time engine-wide events (e.g. sandbox boots, shutdowns, updates).
	//
	// Replaces: GET /v1/events (SSE)
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JsonView], error)
	// Mesh roster/status document for SDK endpoint discovery.
	//
	// Replaces: GET /v1/mesh/status (other /v1/mesh/* admin routes are
	// mesh-internal and remain HTTP).
	MeshStatus(ctx context.Context, in *MeshStatusRequest, opts ...grpc.CallOption) (*JsonView, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SystemService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JsonView], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemService_ServiceDesc.Streams[0], SystemService_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventsRequest, JsonView]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemService_EventsClient = grpc.ServerStreamingClient[JsonView]

func (c *systemServiceClient) MeshStatus(ctx context.Context, in *MeshStatusRequest, opts ...grpc.CallOption) (*JsonView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonView)
	err := c.cc.Invoke(ctx, SystemService_MeshStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
//
// SystemService provides administrative queries and streams engine-wide event feeds.
type SystemServiceServer interface {
	// Retrieves general status, version, capabilities, and system metrics from the host engine.
	//
	// Replaces: GET /v1/info
	Info(context.Context, *InfoRequest) (*JsonView, error)
	// Streams real-time engine-wide events (e.g. sandbox boots, shutdowns, updates).
	//
	// Replaces: GET /v1/events (SSE)
	Events(*EventsRequest, grpc.ServerStreamingServer[JsonView]) error
	// Mesh roster/status document for SDK endpoint discovery.
	//
	// Replaces: GET /v1/mesh/status (other /v1/mesh/* admin routes are
	// mesh-internal and remain HTTP).
	MeshStatus(context.Context, *MeshStatusRequest) (*JsonView, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) Info(context.Context, *InfoRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedSystemServiceServer) Events(*EventsRequest, grpc.ServerStreamingServer[JsonView]) error {
	return status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedSystemServiceServer) MeshStatus(context.Context, *MeshStatusRequest) (*JsonView, error) {
	return nil, status.Error(codes.Unimplemented, "method MeshStatus not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemServiceServer).Events(m, &grpc.GenericServerStream[EventsRequest, JsonView]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemService_EventsServer = grpc.ServerStreamingServer[JsonView]

func _SystemService_MeshStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeshStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).MeshStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_MeshStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).MeshStatus(ctx, req.(*MeshStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmon.v1.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _SystemService_Info_Handler,
		},
		{
			MethodName: "MeshStatus",
			Handler:    _SystemService_MeshStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _SystemService_Events_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vmon/v1/api.proto",
}
